containers/netavark

CODE-OF-CONDUCT.md
OWNERS
README.md

Check in framework for netavark project.

Inital checking

---

.gitignore

My IDE writes some tmp files in there.

add target directory to gitignore

---

.gitignore
src/lib.rs
src/network/mod.rs
src/network/network.rs

Following PR 
* Adds types for `StatusBlock,Network,Subnet,Leaserange `
* Refactor `network` module structure into more generic one.

 network: Refactor mod structure and add types for StatusBlock,Network,Subnet,Leaserange 

---

SECURITY.md

@TomSweeneyRedHat @rhatdan @flouthoc @Luap99 PTAL

SECURITY.md: initial addition

---

src/test/test.rs

Add test to check operation against a mutable parsed NetworkOption

test: add mutablity test

---

Cargo.lock
Cargo.toml
src/commands/setup.rs
src/commands/teardown.rs
src/network/mod.rs
src/network/types.rs
src/network/validation.rs
src/test/test.rs

validate namespace before setup and teardown

---

src/network/core.rs

When invoking `setup` with same config twice we get an error that interface
already exists which is expected. But even then we leave two dandling interface
on host.
* First the one we created for host.
* Second which we were unable to move to container namespace.
We must clean dangling interfaces in case of error. So teardown is not a
mess.
This solves the issue when two consecutive setup commands for same configurations
is invoked.
**How to reproduces the problem solved which is being solved in this PR ?**
```console
sudo ./bin/netavark -f src/test/config/setupopts2.test.json setup /var/run/netns/netnstest
sudo ./bin/netavark -f src/test/config/setupopts2.test.json setup /var/run/netns/netnstest
```
Second setup will fail as it is expected but would also leave dangling
veth pairs on …

core: remove dangling interfaces from host in case of error

---

src/commands/setup.rs
src/network/core.rs
src/network/types.rs

Return a map of StatusBlock describing the network set ups.

Return response to caller (Podman)

---

src/firewall/iptables.rs

The postrouting rule did not get merged for some reason.  Adding now.

Add postrouting rule

---

src/network/core_utils.rs

Following PR makes sure that we create `veth` pair in container namespace
and move other end to host.
Reason: Prevent name collision of interfaces on host.
PR also improves meaning of error messages i.e if config specified `veth` pair already
exists on container namespace tell explicitly.
Closes: https://github.com/containers/netavark/issues/62

core: spin `veth` pair on container namespace and move other end to host.

---

src/commands/setup.rs
src/network/core.rs

We should setup the bridge and firewall rules in the same loop. We also
have to check the given network driver. For now we only support bridge
but we can easily add more in the future.

Refactor bridge setup

---

src/commands/setup.rs
src/commands/teardown.rs
src/network/core.rs

We have to check the network driver before we do teardown.

rework teardown logic like setup

---

src/commands/setup.rs
src/commands/teardown.rs
src/error.rs
src/lib.rs
src/main.rs

JSON errors to podman

---

src/network/core_utils.rs

add helper to check if bridge has any connected interface
Usage
```rust
//count interfaces on bridge
if let Ok(vector) =  bridge_count_connected_interfaces("cni-podman0") {
println!("{:?}", vector.len());
}
```

core: add `bridge_count_connected_interfaces` to check if bridge has any connected interface

---

src/network/core.rs

core: generate host veth name early in the stack

---

src/commands/setup.rs
src/commands/teardown.rs
src/firewall/iptables.rs
src/network/core.rs
src/network/core_utils.rs
src/network/internal_types.rs

enable ipv6 connection handling

initial ipv6 implementation

---

src/firewall/iptables.rs
src/network/core_utils.rs

Add support for better error messages and also things to help integration test pass UDP and IPv6.

Fix UDP and network stuff

---

src/firewall/varktables/types.rs
test/100-bridge-iptables.bats

Use the ability of ranges with iptables instead of creating multiple
rules for each port.

Add port ranges

---

Makefile

make: remove vendor from all

---

.cirrus.yml

Nothing drastic, simply newer/updated packages.

Cirrus: Use newer VM images

---

src/dns/aardvark.rs

First refactor the aardvark spawn code a bit to remove duplication.
Second, aardvark should not use stdout/err from netavark. Since aardvark
is a long running process the output streams could be closed when it
tries to write something.
TODO We should setup a log file when we are on debug logging level.

set stdout/err to /dev/null for aardvark

---

src/commands/setup.rs
src/dns/aardvark.rs
src/main.rs

add option to configure aardvark-dns path

---

OWNERS

@flouthoc @baude @mheon @cevich @Luap99 PTAL

OWNERS: add cevich

---

Cargo.toml
README.md
RELEASE_NOTES.md
test/001-basic.bats

Bump to v1.0.0-rc1

---

netavark.spec.rpkg

@Luap99 @flouthoc @baude @mheon PTAL.

COPR: fix build with git-core builddep

---

netavark.spec.rpkg

@flouthoc @Luap99 @baude @mheon @rhatdan @cevich PTAL
@cevich this should handle the dependency issue on f34.

COPR: update dependencies and provides

---

src/firewall/varktables/types.rs

remove hashed networks chains and leave no turds behind.

Removed hash iptables rules

---

src/commands/setup.rs
src/commands/teardown.rs
src/dns/aardvark.rs
src/firewall/mod.rs
src/network/core.rs
src/network/core_utils.rs

We should never ever panic. Podman should always present a human
readable error string. If netavark panics this will not be possible.

no more panics

---

DISTRO_PACKAGE.md

@baude @flouthoc @mheon @rhatdan @TomSweeneyRedHat  @Luap99 PTAL.

DISTRO_PACKAGE.md: info for packagers and package users

---

Cargo.lock
Cargo.toml
RELEASE_NOTES.md
test/001-basic.bats

- update release notes
- cut v1.0.1
- bump to v1.0.2-dev

v1.0.1 Release

---

.cirrus.yml
Makefile
contrib/cirrus/lib.sh
contrib/cirrus/runner.sh
contrib/cirrus/setup.sh
src/commands/teardown.rs
src/dns/aardvark.rs
src/network/core.rs
src/network/core_utils.rs

Performs builds across various archs to make sure build sanity is
maintained across archs

build: run build sanity for various architecture

---

RELEASE_NOTES.md

release notes for v1.0.2

---

src/network/core.rs
test/300-macvlan.bats

We should try to avoid mutable vars when not needed.
Also add tests for all macvlan modes.

bidge/macvlan: simplify option parsing

---

Cargo.lock
Cargo.toml
RELEASE_NOTES.md

* Updated dependenciess
* Simplified option parsing for bridge/macvlan
* Added support for an ipam `none` driver

Release v1.0.3

---

README.md

Hi, I've added a requirement for podman 4.0+ as many people are getting confused.

Added a Requirement for podman 4.0+

---

Cargo.toml

Update `cargo.toml` with fields necessary for packaging.

cargo.toml: update info fields for packaging

---

Cargo.lock
Cargo.toml
RELEASE_NOTES.md

No branch, since we only seem to do RHEL branches on this repo.

Bump to v1.1.0

---

.cirrus.yml

Cirrus: Replace AWS credentials

---

Cargo.lock
Cargo.toml
RELEASE_NOTES.md

* Reworked how netavark calls aardvark
* Implemented locking when committing
* Remove bridge only when no containers are attached
* Updated versions of libraries where possible

Release1.2.0

---

.cirrus.yml
Makefile

This should get https://github.com/containers/aardvark-dns/pull/234 un-stuck.

Cirrus: CI branch updates

---

src/network/netlink.rs

We have a merge problem on main, one PR used functions there were removed in another.
https://github.com/containers/netavark/pull/448
https://github.com/containers/netavark/pull/447
Sorry I should have noticed this and rebased.

fix broken build

---

Makefile

This tool creates a much small vendor dir since we can only include the linux dependencies. Our current one on main is 46 MB big and with cargo vendor-filterer it is only 6 MB.
see https://github.com/coreos/cargo-vendor-filterer
Fixes #347

use cargo-vendor-filterer to create vendor tarball

---

Cargo.lock
Cargo.toml

Correct dev version

---

.cirrus.yml
contrib/cirrus/runner.sh
src/dns/aardvark.rs
src/network/bridge.rs
src/network/core_utils.rs

Includes mandown in the image.
ref https://github.com/containers/automation_images/pull/241

update CI images

---

.cirrus.yml

Vim mode-switching got the better of me.

Cirrus: Fix two minor typos.

---

contrib/cirrus/cache_groom.sh

See https://github.com/containers/aardvark-dns/pull/282

Minor: Add script remote re-use comment.

---

Cargo.lock
Cargo.toml
src/network/netlink.rs

They contain breaking changes but nothing major, just moved same type definitions.

update netlink-packet-{route,core} to 0.15 and 0.5

---

.github/dependabot.yml

Disable Dependabot in favor of Renovate

---

src/commands/dhcp_proxy.rs

If there is an error during setup we should return the error so that netavark can exit > 0 and systemd will report this as failure.

dhcp-proxy: correctly exit > 0 on errors

---

Cargo.lock
Cargo.toml
src/network/bridge.rs
src/network/constants.rs
src/network/core_utils.rs
src/network/vlan.rs

see https://bugzilla.redhat.com/show_bug.cgi?id=2183896

[v1.5] backport bclim option

---

src/commands/setup.rs

We should only say dns is disabled because of the missing binary when dns was requested. If there are no dns entries we should not log this line. Also inlcude the path in the log so users know which path we want.

aardvark: fix missleading dns disabled log

---

.cirrus.yml
README.md
docs/Makefile
rpm/netavark.spec

docs: Convert markdown with go-md2man instead of mandown

---

Cargo.lock
build.rs

update chrono crate and replace deprecated call

update chrono crate

---

examples/host-device-plugin.rs
src/commands/setup.rs
src/commands/teardown.rs
src/commands/version.rs
src/dhcp_proxy/cache.rs
src/dns/aardvark.rs
src/error/mod.rs
src/firewall/firewalld.rs
src/firewall/iptables.rs
src/firewall/mod.rs
src/firewall/varktables/helpers.rs
src/firewall/varktables/types.rs
src/network/bridge.rs
src/network/core_utils.rs
src/network/macvlan_dhcp.rs
src/network/netlink.rs
src/network/vlan.rs
src/plugin.rs
src/test/netlink.rs

Lot's of warnings from clippy about inline variable use

Fix clippy warnings about formatting

---

Cargo.lock
Cargo.toml

updating tonic and prost works better when done together

Bump tonic and prost

---

.packit.yaml

[CI:BUILD] Packit: tag @lsm5 on copr build failures

---

src/network/bridge.rs
src/network/constants.rs
test/600-bridge-vrf.bats
test/testfiles/simplebridge-vrf.json

This pull request adds support for adding a bridge created by netavark to a VRF (#729) .

Add vrf support for bridges

---

Cargo.lock
Cargo.toml

one manual fix to pin clap to 4.3 as this requires rust v1.70

run cargo update

---

src/dhcp_proxy/dhcp_service.rs
src/network/macvlan_dhcp.rs

netavark: dhcp_proxy: skip set gateway if missing

---

Cargo.toml
src/commands/setup.rs
src/commands/teardown.rs
src/firewall/mod.rs
src/main.rs

Change the firewall driver with the command option
Signed-off-by: unknowndevQwQ <unknowndevQwQ@pm.me>

feat: added the --firewall-driver option

---

Cargo.lock
Cargo.toml
DISTRO_PACKAGE.md
rpm/netavark.spec

This allows us to publish on crates.io as well.

update to nftables release 0.3 from crates.io

---

README.md

update README with nftables support

---

Cargo.lock
Cargo.toml

something is failing with renovate's PR so doing the update manually.

Update to nix-0.28.0

---

src/network/macvlan_dhcp.rs
src/network/vlan.rs

netavark: dhcp_proxy: use dns servers from dhcp lease

---

Cargo.lock
Cargo.toml

This fixes a dhcp flake.
Fixes #618

update mozim to 0.2.4

---

src/dns/aardvark.rs

Big ops, we didn't handle any error when starting aardvark-dns. While we waited for the fork to happen we never checked the exit status of the command thus all errors were silently ignored. Also the command is supposed to capture the error message so we can return it as proper error string to podman. Before we should wrote to stderr which will not show up for podman-remote users.
Of course right now aardvark-dns doesn't actually report many errors so we never cought this but I am trying to make bind failures visible to users so we need this.

fix aardvark-dns error handling

---

Cargo.lock
Cargo.toml
src/commands/firewalld_reload.rs
src/firewall/firewalld.rs

This PR was basically done in #1025 by a contributor Blair Noctis.  His PR got stuck in a rebase problem and I have simply taken his diff and worked out the rebasing issue.  Thanks so much to Blair for his work.

Updated to zbus4

---

Cargo.lock
Cargo.toml
RELEASE_NOTES.md

* Fixed bug where port forwarding rules might not be removed correctly on nftables
* Add DNS DNAT rules first with nftables

Release v1.13.0

---

.cirrus.yml
Makefile
src/dhcp_proxy/cache.rs
src/firewall/firewalld.rs
src/firewall/state.rs
src/firewall/varktables/types.rs
src/network/bridge.rs
test-dhcp/helpers.bash

Now fedora 41 and new lint fixed for rust 1.82

New CI images

---

Cargo.lock
Cargo.toml
RELEASE_NOTES.md
src/commands/setup.rs
src/firewall/nft.rs
test/100-bridge-iptables.bats
test/250-bridge-nftables.bats
test/testfiles/bridge-port-hostip.json

Backports of https://github.com/containers/netavark/pull/1131 and https://github.com/containers/netavark/pull/1123 and the final release notes + version bump

[v1.13] Release v1.13.1

---

.cirrus.yml

https://github.com/containers/automation_images/pull/398

New VM Images

---

Cargo.lock
Cargo.toml
src/dhcp_proxy/cache.rs
src/dhcp_proxy/proxy_conf.rs
src/network/vlan.rs

minor updates for deprecated calls

fix(deps): update rust crate rand to 0.9.0

---

.cirrus.yml
Makefile
contrib/cirrus/runner.sh
docs/Makefile

see commits
Fixes #1178 
Fixes #1179

Makefile: several fixes

---

src/firewall/firewalld.rs

The code was written to work with a boolean property. Unfortunately, it's not a boolean, it's a DBus Variant holding a String which can be either "yes" or "no". This, unfortunately, complicates our decoding code somewhat considerably.
I don't know how this actually worked when I tested it in the first place, unless the API type changed in firewalld before final release, which I don't *think* happened? Fortunately, the code here is written to be very forgiving of errors, but I added some warning logs to give us a trail if stuff starts blowing up in the future (because Variant means the type can, theoretically, change in the future, which would be unpleasant).
Fixes https://issues.redhat.com/browse/RHEL-80266

Fix detection of Firewalld's StrictForwardPorts property

---

.github/workflows/release.yml
.gitignore
Makefile

Automatically create release from tag, and build artifacts. Release notes are pulled from RELEASE_NOTES.

GHA: Automate release
