Cargo.lock, Cargo.toml, src/commands/setup.rs, src/commands/teardown.rs, src/lib.rs, src/network/mod.rs, src/serialize.rs
Following PR contains types which will be consumed by netavark.
* Types
* Deserializer to consume types from files.
* Serializer incase we need to flush back types back to json. (We can remove this later if not needed).
=> network: Add types and deserializer for NetworkOptions

Makefile, src/main.rs, src/test/config/setupopts.test.json, src/test/mod.rs, src/test/test.rs
Initial tests setup.
* Covers deserialize and struct loading test for network options.
Usage
```console
make test
```
=> tests: Add tests for Network Setup Options deserializer

README.md
There's a significant number of non-IRC users in the bridged rooms,
both Matrix and Discord. So, we should mention those options too.
@flouthoc @Luap99 @mheon @TomSweeneyRedHat PTAL
=> README.md: Point to Podman's channels

.cirrus.yml
Basic wireup for testing in the cirrus container.  At first, we just use
a container.
=> Add cirrus testing

src/commands/teardown.rs, src/network/core.rs, src/network/core_utils.rs
Implements teardown which is responsible for removing container
interfaces and performing cleanups.
Usage
```console
netavark -f <config> teardown <networknamespace>
```
=> teardown: implement teardown for removing container interfaces or container `veth`.

src/network/core.rs, src/network/core_utils.rs
We must turn up loopback while `setup` cause podman will not do that for
us.
=> core: turn up  `lo` adapter in ctr namespace during setup

src/firewall/iptables.rs
There was a typo in the iptables rule exists check, we have to read the NAT table.
=> Fix POSTROUTING rule exists check

src/network/core_utils.rs, src/test/config/twoNetworks.json
The default route will be added for each connected network, so when you
would try to use two networks it would fail because the default route
was already added. While we could ignore eexist error this is not what
we want.
If we only have one route and disconnect the network with the default
route we will loose internet connectivity. To best way is to have each
network create the default route. This can be done by not setting the
NLM_F_EXCL flag for the netlink request.
Also see this CNI bridge plugin PR which does the same there: https://github.com/containernetworking/plugins/pull/615
=> netlink add ecmp route

src/network/core.rs, src/network/core_utils.rs, src/network/types.rs
We should parse the types early so that we do not run in unexpected
errors later.
This commit also fixes the following issues:
The gateway ip can be empty for internal networks.
The subnet parsing was broken for ipv6.
=> network setup use proper ip types instead of strings

Cargo.lock, Cargo.toml, src/lib.rs, src/network/types.rs
We're already doing it the (IMO more preferred) way of using
`serde = ... features = ["derive"]` so this was just unused.
=> Drop unnecessary `serde_derive` crate

Cargo.lock, Cargo.toml, src/firewall/firewalld.rs, src/firewall/mod.rs
Presently, we use one zone for all interfaces, with one policy for that zone to enable masquerading. Every time a zone or policy is added, we need to do a firewall reload, so we can only make one zone of each (the very first time netavark runs) unless we want to wipe out our port-forwarding rules every time we run. This differs a lot from my original architecture, but I think it's the best we can do given the constaints.
Presently compiles, but does not actually work. When I make the dbus calls manually via busctl is does work. I'm slowly tracking down why, but debugging dbus calls like this is painful.
=> Initial implementation of firewalld backend

Cargo.lock, Cargo.toml, src/network/core_utils.rs
Following PR makes these following changes
Adds core methods to create macvlan interface.
* Creates macvlan for specified master veth with given mode.
* Moves and rename macvlan to container namespace.
* Turn up macvlan interface.
* Update `Cargo.toml` to point to `master` of `rtnetlink`. After https://github.com/little-dude/netlink/pull/194
=> core: add methods to configure `macvlan` interface for container and point to latest `rtnetlink`

src/network/core.rs, src/network/core_utils.rs
Fix error wrapping and formatting. Remove unnecessary `{:?}` debug which escapes and prints entire `struct` for debugging.
formatter from errors.
Tidy up errors.
Final `Error: Custom` gets removed after https://github.com/containers/netavark/pull/47
Before:
```console
Error: Custom { kind: Other, error: "failed configure bridge and veth interface: Custom { kind: Other, error: \"Error while configuring network interface from container namespace: Custom { kind: Other, error: \\\"interface ethsomething0 already exists on container namespace\\\" }:\" }" }
```
* with https://github.com/containers/netavark/pull/47
```console
{"error":"failed configure bridge and veth interface: failed while configuring network interface from container namespace: interface ethsomething0 already exists on …
```
=> netavark: fix error wrapping and formatting

src/commands/setup.rs, src/commands/teardown.rs, src/network/validation.rs, src/test/test.rs
The return result of `ns_checks()` was not used. It also only returns an
bool which is not helpful because it hides the actual error message.
Second, the teardown command should not check for a valid netns and just
try to cleanup as much as possible.
=> Fix non working netns path check

src/network/core.rs, src/network/types.rs, src/test/config/setupopts.test.json, src/test/config/setupopts2.test.json
Some field names are confusing. Change them so that they make more sense
to the reader.
I also added comments to the types to provide more context.
also see https://github.com/containers/podman/pull/12319
=> rename nettypes fields

Cargo.lock, Cargo.toml, src/commands/setup.rs, src/firewall/firewalld.rs, src/firewall/iptables.rs, src/firewall/mod.rs, src/network/core_utils.rs, src/network/types.rs
when using the iptables firewall driver, we can no forward ports from
the container host to the container.
i.e. curl http://localhost:8080
=> Enabled portfw'ing for iptables

src/error.rs
We already get the exit code when the program exits so there is no need
to include it in the json. Podman will reject unknown fields to prevent
reading unexpected stuff.
=> Do not serialize the errno field

src/main.rs
There is no value on logging the timestamp IMO. When I make the netavark
interface log to syslog in podman I get 3 timestamps. First the syslog
itself, then the logrus in podman and then netavark env logger.
I think we can just remove this one without breaking anything.
=> Do not log the timestamp

src/commands/setup.rs, src/commands/teardown.rs, src/firewall/firewalld.rs, src/firewall/iptables.rs, src/firewall/mod.rs, src/network/core_utils.rs, src/network/types.rs, src/test/config/portmapping.json
When a container is cleaned up, podman will call netavark to teardown
the network information.  We need to clean up any container specific
iptables rules.
Once we have a fn to detect if the container is the last on the network,
then we can also teardown network specific iptables rules.
=> Initial checkin for teardown iptables

src/commands/setup.rs, src/commands/teardown.rs, src/firewall/firewalld.rs, src/firewall/iptables.rs, src/firewall/mod.rs, src/network/internal_types.rs, src/network/mod.rs, src/network/types.rs
When calling setup_network, teardown_network, setup_port_forward, and
teardown_port_forward we now use defined structs for input.
=> Use structs for input

Cargo.lock, Cargo.toml, src/commands/setup.rs, src/commands/teardown.rs, src/network/constants.rs, src/network/core.rs, src/network/core_utils.rs, src/network/mod.rs, src/test/config/setupoptsmacvlan.test.json
Following PR adds extends `setup` command to allow configuring `macvlan`
if specified in config as a `driver`.
When merged following should work with `macvlan` config.
```console
sudo ./bin/netavark -f <config_with_macvlan> setup /var/run/netns/netnstest
```
=> core: add support for setting up `macvlan` driver from config

Makefile
Without this, running 'make test' will fail to execute if the `test` directory timestamp is current.
=> Fix make: 'test' is up to date.

.cirrus.yml, contrib/Dockerfile, contrib/cirrus/lib.sh, contrib/cirrus/runner.sh, contrib/cirrus/setup.sh, hack/get_ci_vm.sh
Prior to this commit, CI ran entirely in a container environment.  This
was very much less than ideal, since actual network/firewall
manipulations could not be exercised.  With this commit, everything will
execute on the same VM images and image-build workflow used by all the
other containers-org project automations.
Note: Given all other projects generally use golang, the VM images here
are *NOT* tailored to a rust project.  Unfortunately that means
performing runtime updates/installs and using cache to reduce the dnf
repo. Metadata/package downloading.  These aspects can be removed once
dedicated netavark VM images are realized and implemented in a future
commit.
=> Cirrus: Switch CI onto VMs from containers

src/commands/setup.rs, src/commands/teardown.rs, src/error.rs, src/main.rs
If the NetavarkError is wrapped twice so you get json in the actual error
message field. To fix this we need to keep the default string display
and use an explicit print_json function.
This is the current message `{"error":"{\"error\":\"No such file or directory (os error 2)\"}"}`
Now it looks like this `{"error":"No such file or directory (os error 2)"}`
=> Fix double json in error message

Cargo.toml
Fedora's Rust packaging guidelines recommend excluding unnecessary files
from Cargo.toml itself.
https://docs.fedoraproject.org/en-US/packaging-guidelines/Rust/#_excluding_unnecessary_files
PTAL
=> Cargo.toml: exclude unnecessary files from crate

src/firewall/iptables.rs
We need to add the NETVARK-XXX chain to the POSTROUTING chain. Otherwise
the chain will just be skipped.
=> add missing iptables rule for nat

.cirrus.yml
This is needed to improve the initial build performance, which despite
caching `$CARGO_HOME` still takes ~10min to complete initially.
=> Cirrus: Use extra CPU/Mem for build task

src/network/core.rs, src/network/core_utils.rs
Netavark config accepts `MTU` as network option so allow users to
configure the same for both `bridge` and `veth` interfaces if defined.
Closes: https://github.com/containers/netavark/issues/107
=> core: allow users to configure `MTU` for `bridge` and `veth` interfaces from config

src/network/core.rs, src/network/core_utils.rs
Explicitly required kernel parameters like `accept_ra` and `accept_dad` are
only needed for interface when we are using `ipv6` not `ipv4`.
Standard netavark configuration has a field `ipv6_enabled` which should be enough
for us to propagate configuration to lower utility functions in the
stack.
=> core: configure required kernel parameters `accept_ra` and `accept_dad` for `ipv6` not for `ipv4`

.autocopr/README, .autocopr/netavark.spec
This commit along with an upstream  webhook
will automatically build an rpm at
`rhcontainerbot/podman-next` .
@flouthoc @baude @mheon @Luap99 @rhatdan PTAL
=> add spec file for automated copr builds

.autocopr/netavark.spec
In the case of multiple PR merges and thus multiple COPR builds
everyday, it would be good to also include HHMMSS in the release tag.
@flouthoc @baude @mheon PTAL
=> include %H%M%S in the release tag

src/network/core.rs, src/network/core_utils.rs
Netavark accepts static `MAC` for container interfaces, allow netavark
to configure static `MAC` address for container interface from config.
Closes: https://github.com/containers/netavark/issues/106
=> core: add support for setting static `MAC` for container interface.

.cirrus.yml, Makefile, contrib/cirrus/runner.sh, test/001-basic.bats, test/100-bridge-iptables.bats, test/200-bridge-firewalld.bats, test/300-macvlan.bats, test/README.md, test/helpers.bash, test/testfiles/firewalld-dbus.conf, test/testfiles/ipv6-bridge.json, test/testfiles/macvlan.json, test/testfiles/simplebridge.json
Add bats tests for netavark. The test run netavark in completely
separate network namespaces to not leak any information on the host. The
test runs with the iptables driver but also with the firewalld driver
see test/020-firewalld.bats. This is important to cover all firewall
driver code paths.
You can run the tests with `sudo bats test/` or `podman unshare
--rootless-netns bats test/`. Note that the `--rootless-netns` flag is
called `--rootless-cni` for podman < v4.0.
=> Add netavark integration tests

src/network/core_utils.rs
Disable duplication address detection inside container namespace only if
its `ipv6` not `ipv4`
This is similar to : https://github.com/containers/netavark/pull/110
After: https://github.com/containers/netavark/pull/113
=> core: disable duplication address detection inside container only if its `IPv6`

.cirrus.yml, .gitignore, Makefile, contrib/cirrus/runner.sh
This is fairly complex unfortunately, but should reduce the amount of re-compiling we do in CI.  It also makes the `make` + `cargo` situation clearer WRT all the `.PHONY` targets, and disambiguation of the var, args, and term `target`.
Lastly, the "total success" aggregation task now uploads the compiled + tested `netavark` and `netavark.debug` binaries.  The intention is to make use of these in downstream CI (like podman).
=> Improve Makefile + Caching in CI

.cirrus.yml, contrib/cirrus/setup.sh
Image comes from https://github.com/containers/automation_images/pull/101
The primary benefits to using a dedicated netavark VM image are:
* Predictable environment changes.  Underlying packages are only updated when we decide to build + incorporate an updated image.
* Improved Speed/efficiency of CI.  Remove the 1-2minutes spent in each task updating/installing required packages, since they're pre-installed in the image.
Total runtime in this PR: 11-13min vs 18-20min in #109 
***Depends on:*** https://github.com/containers/netavark/pull/109
=> Cirrus: Dedicated VM images for CI

src/commands/setup.rs, src/commands/teardown.rs, src/firewall/firewalld.rs, src/firewall/iptables.rs, src/firewall/mod.rs, src/firewall/varktables/helpers.rs, src/firewall/varktables/mod.rs, src/firewall/varktables/types.rs, src/network/internal_types.rs, test/100-bridge-iptables.bats, test/helpers.bash
Switch to a model where we use a rule generator approach for setup and
teardown.  This eliminates a significant amount duplicate code.
=> Refactor iptables

src/commands/setup.rs, src/commands/teardown.rs, src/network/core.rs, test/100-bridge-iptables.bats, test/testfiles/internal.json
An internal network should have no nat or port mappings as it is
supposed to a "closed" network.
Fixes #: 105
=> Support internal networks

src/firewall/iptables.rs, src/network/core_utils.rs
I was randomly looking at another PR, and noticed that in about
half the cases, we heap allocate a `String`, but then use `as_str()`
to borrow it briefly.  In other places we directly use `&str`.
It maximizes flexibility for the caller to use `AsRef<str>`; then
we don't need a `.as_str()` dance, we can just directly pass ownership
of the string into the function.
To pick one other random real world example of this, see:
https://github.com/rust-lang/rust/blob/9bb77da74dac4768489127d21e32db19b59ada5b/compiler/rustc_errors/src/diagnostic_builder.rs#L198
=> Use `AsRef<str>` for sysctl bits

test/100-bridge-iptables.bats
* Add tests for `port-forwarding` with `range` for `ip=dualstack`
* Test for `internal network` was removed in https://github.com/containers/netavark/pull/138 so add it again.
=> tests: add tests for `port-forwarding` with `range` for `ip=dualstack` and restore `internal network`

src/commands/setup.rs, src/commands/teardown.rs, src/firewall/iptables.rs, src/firewall/varktables/types.rs, src/network/internal_types.rs
This is necessary to simplify operation for port forwarding via firewalld. Instead of requiring two separate calls to add and remove port forward rules for v4 and v6, both are now carried in the struct, which means I don't have to worry about one of my DBus calls messing up the other. For iptables it's mostly a wash, the code gets a slight bit more complex, but not significantly.
=> Change to making only a single call to setup/tear down

src/firewall/varktables/types.rs, test/100-bridge-iptables.bats, test/helpers.bash
add the ability to handle port mapping to a specific host ip address
instead of 0.0.0.0.
=> portmap to specific host ip address

src/network/core.rs, src/network/core_utils.rs, test/100-bridge-iptables.bats
thread.join() returns a result which contains the return result from the thread
so we have to get the actual error from the result.
Added a test to make sure it works.
=> handle errors from the netns properly

src/network/core.rs, src/network/core_utils.rs, test/300-macvlan.bats, test/testfiles/macvlan-mtu.json
Netavark config accepts `MTU` as network option so allow users to
configure the same for `macvlan` interface.
See https://github.com/containernetworking/plugins/blob/master/plugins/main/macvlan/macvlan.go#L181
Follow up PR to: https://github.com/containers/netavark/pull/111
Closes: https://github.com/containers/netavark/issues/152
=> core: add support setting for `MTU` on `macvlan` interface from netavark config

src/network/core.rs, src/network/types.rs
Netavark does not configures name servers if they are on non-default
networks. As a result they don't resolv queries to IP of gateways and
reach to default IP address.
Following PR is needed for containers which are not on default `podman`
network so `podman can configure appropriate resolver.
=> core: configure `DNS nameservers` for containers if needed.

src/commands/setup.rs, src/commands/teardown.rs, src/dns/aardvark.rs, src/main.rs
* Spawns aardvark server for `rootless` containers using `systemd-run`
within same `scope` and `--user`.
* Also use regular child process for environments where `systemd-run` is
not present.
=> dns: Enables name resolution for `rootless` containers

.autocopr/netavark.spec
This should be gotten rid of once the copr infra upgrade to f35 is
complete
@baude @mheon @Luap99 @rhatdan PTAL
=> copr workaround: temporarily re-add .autocopr/netavark.spec

Makefile
You will need to run `make` and `make install` separately.
We will not need any `-nobuild` targets which should make life a little
easier for packagers.
@flouthoc @baude @mheon @cevich @Luap99 PTAL.
=> Makefile: install target independent of build

src/firewall/varktables/types.rs
We should not be removing the HOSTPORT_MASQ rule from the POSTROUTING table as this can effectively ruin port mapping on other running containers.
=> Do not remove all iptables rules on teardown

src/commands/setup.rs, src/dns/aardvark.rs, src/network/types.rs
Podman can pass network aliases via `--network-alias` so netavark should read it and pass
relevent config to aardvark
Supports DNS resolution with network aliases.
=> dns: support for container `aliases` if specified from container managers.

src/network/constants.rs, src/network/core.rs, src/network/types.rs
Podman setup expects a default search domain in `/etc/resolv.conf` i.e
`dns.podman` lets supports that.
=> core: populate default search domain in `/etc/resolv.conf`

src/firewall/varktables/types.rs, src/network/core.rs, src/network/core_utils.rs
Unnecessary use of to_string() throws an lint error since v1.58 so we
should fix that.
=> Fix lint problems with rust v1.58

Cargo.lock, src/commands/setup.rs, src/commands/teardown.rs, src/dns/aardvark.rs, src/main.rs
This saves startup time since aardvark does not have to read the same
config twice. Also improve the error handling. We should not ignore errors
such as EPERM, etc...
=> start aardvark only after we write config

src/network/core.rs, src/network/core_utils.rs
Use .map() to iterate through mac address.
Get macvlan master_interface in a single match block.
Remove unneeded .to_string() calls.
=> cleanup: simplify code

src/network/core_utils.rs, test/100-bridge-iptables.bats
I think the upgrade to rtnetlink broke the connected interfaces detection.
I added a test to ensure it works now correctly.
=> fix bridge teardown logic

src/dns/aardvark.rs
set RUST_LOG for aardvark
keep aardvark stderr open with debug log level
It is important to read stderr output from aardvark to debug things like
panics. Since keeping the stderr open can cause EPIPE when aardvark tries
to write to it and the user closed the original stderr, this is only done
for debug/trace level.
=> set RUST_LOG for aardvark and keep aardvark stderr open with debug log level

src/dns/aardvark.rs
When we have debug level we want stderr connected. If this is not the
case we should use /dev/null.
Also do not connect stdin and use Stdio::inherit() instead of the unsafe
call.
=> fix aardvark output logic

src/firewall/varktables/types.rs, test/100-bridge-iptables.bats
When we have two containers on different networks running and stop one
of them we still need the NETAVARK_FORWARD rule in the FORWARD chain.
If this rule is removed the containers lose connections if the default
FORWARD policy is DROP.
test: add iptables rule check
Add tests to check the exact iptables rules.
=> do not remove NETAVARK_FORWARD rule on teardown 

src/firewall/varktables/types.rs, test/100-bridge-iptables.bats, test/200-bridge-firewalld.bats, test/helpers.bash
In my (limited) testing, this fixes the issue described in #232. I'm not very familiar with netavark or iptables but I hope I didn't miss anything. If there are issues, I'd be happy to improve the solution with input on what's lacking.
I think the test file `ipv6-bridge.json` could be changed to show the behavior from #232 but I'm not sure how to exactly.
I skimmed the firewalld.rs and I think the issue is present there too. I think I can't test the firewalld implementation since my system is still using firewalld 1.0.1 and the bats tests emit `(skipped: TODO: Firewalld driver swapped with iptables until firewalld 1.1.0)`.
=> Add host_ip and container_ip version matching to iptables `get_port_forwarding_chains`

src/network/core.rs, test/300-macvlan.bats
Gateway must be added as default route to `macvlan` interface.
Since gateway is already there in netavark config following config just
makes sure that we parse and add it to interface's default route instead
of adding no route at all.
Closes: https://github.com/containers/netavark/issues/234
=> core,macvlan: add `gateway` from spec as default route to `macvlan` interface

.cargo/config.toml, .gitignore, DISTRO_PACKAGE.md, contrib/cirrus/runner.sh
We should not try to build with deps from the vendor directory locally.
This will force me to run make vendor manually if I pull in new deps.
When distros want to build with bundeld deps they should a) download
the linked vendor tarball which we should provide for the releases and
b) create the cargo config since to let cargo use the vendor dir.
```
tar xvf %{SOURCE1}
mkdir -p .cargo
cat >.cargo/config << EOF
[source.crates-io]
replace-with = "vendored-sources"
[source.vendored-sources]
directory = "vendor"
EOF
```
see https://src.fedoraproject.org/rpms/rust-coreos-installer/blob/rawhide/f/rust-coreos-installer.spec#_86
=> use local cargo dependencies

src/network/core.rs, test/300-macvlan.bats, test/testfiles/macvlan-internal.json
Higher level container managers like `podman` can choose to create `macvlan` networks
with no default gateway by setting `--internal` as `true` in netavark
spec.
This can allow other tools and users to create macvlan networks without
default gateway routes but container manager like `podman` must allow
`macvlan` with `--internal` flag.
Netavark Implementation for: https://github.com/containers/podman/issues/13319
=> macvlan: support `--internal` `macvlan` network with no default gateway in routes

netavark.spec.rpkg
The __cargo_skip_build isn't really useful to us. Netavark will always
be archful so this conditional is best removed.
This will also fix a build issue on rhel 8 envs.
@baude @flouthoc @Luap99 @mheon PTAL, trivial change to fix rhel8 auto builds on the fedora `rhcontainerbot/podman-next` copr.
EDIT: Description update.
=> netavark.spec.rpkg: remove unnecessary conditional

.cirrus.yml
=> Add Fedora-36 native compile

.cirrus.yml
Because the rust toolchains can differ immensely depending on the
distribution and because we pull the latest rust toolchain in the rest
of the netavark CI, we need to perform test builds by distributions.
Fedora 35 already exists.  Adding CentOS9 and Ubuntu 20.04.4 LTS.
=> Add more distribution rust builds

src/dns/aardvark.rs
According to sd_booted(3) checking if /run/systemd/system exists is good
enough to see if systemd is booted.
While this check is not perfect it will at least allow us to use it
inside a container where systemd binaries are installed but the
container is run without systemd, see
https://github.com/containers/podman/issues/13533
Another option would be to use the systemd dbus API. I gave it a try but
couldn't figure out the exact format we have to send and also had
trouble connecting to the rootless session.
For now this should help to get aardvark working inside a container.
=> aardvark: only use systemd-run when systemd is available

.cirrus.yml, Cargo.lock, Cargo.toml, build.rs, src/commands/version.rs, src/main.rs
Backport commit bdaef37da836.
We only need the version, build time, rust target triple, and git commit
for the version command. These values can easily be generated with little
code so we do not need an extra dependency for this.
The main reason for this change is that vergen will fail if no git
commit is found. On distro build systems this is often the case since
they build from a source tar without the git repo. Instead of erroring
we should just show an empty commit in the version output.
=> [v1.0.1-rhel] Backport "Drop vergen dependency"

src/network/core.rs
Simplify the logic a bit by using IpNet:new() which works for ipv4 and
ipv6 instead of having to use a match.
=> bridge/macvlan: use IpNet::new() to create subnet

src/network/constants.rs, src/network/core.rs, src/network/core_utils.rs, src/network/internal_types.rs, src/network/types.rs, test/100-bridge-iptables.bats, test/300-macvlan.bats
Allow creating interfaces only with no ip addresses assigned.
Also combine some duplicated code for bridge/macvlan.
Ref https://github.com/containers/common/pull/967
=> add ipam driver none support

test/helpers.bash
Right now `assert t:[1] != t:[1]` passes. This is obviously incorrect
and some test might not be working correctly because of this. We have to
special case this like the "==" case.
I discovered this in buildah, since we use the same logic here we should
fix it to prevent unexpected bugs.
=> test/helpers.bash: assert handle corner cases correctly

src/network/core.rs
After the recent cargo update validate fails because of using `let`
binding on unit value further we are not interested in using this value
so drop it.
See: https://rust-lang.github.io/rust-clippy/master/index.html#let_unit_value
Fixes issue in: https://github.com/containers/netavark/pull/322
Fixes broken CI on current main branch: https://cirrus-ci.com/build/4539848676605952
=> core,lint: omit the unused `let` binding

.cirrus.yml, Makefile, contrib/cirrus/runner.sh
In order to test `aardvark-dns` (and maybe elsewhere) a recent binary
build of netavark from the CI system is needed.  Previously this was
always an `x86_64` binary along with a `.debug` version.  Add support for
archiving both `arm` (32 bit) and `aarch64` binaries.  Name them with
the architecture-target as a suffix so they may be distinguished from
the (necked) `netavark` binary.
e.g. `bin/netavark.aarch64-unknown-linux-gnu`
*note:* A VM image update was also required
=> Cirrus: Gather arm and aarch64 netavark binaries

Cargo.toml
Need to lock build deps for publishing it cannot be wildcard.
=> Cargo.toml: lock build-deps for publishing

src/commands/setup.rs, src/commands/teardown.rs, src/dns/aardvark.rs, src/firewall/iptables.rs, src/firewall/varktables/types.rs, src/network/internal_types.rs, test/100-bridge-iptables.bats, test/200-bridge-firewalld.bats, test/helpers.bash, test/testfiles/connectbridge.json
add support for a new option "isolate", a boolean that determines whether or not a network
can send/recieve data outside of its bridge. This is done by creating a new chain "NETAVARK_ISOLATION" that drops external outgoing connections
resolves #154
Signed-off-by: cdoern <cbdoer23@g.holycross.edu>
=> isolate podman networks

test/100-bridge-iptables.bats, test/testfiles/connectbridge.json
Fix some problems with the isolation test. Fix the overlapping subnets
to make sure we correctly route. Add `-w 1` to ping to prevent it from
just hanging. Turn off dns on the network since we do not need it and
fix the test comments to actually reflect what we do.
=> fixup isolate networks test

src/firewall/iptables.rs, src/firewall/varktables/types.rs, test/100-bridge-iptables.bats, test/helpers.bash, test/testfiles/isolate1.json, test/testfiles/isolate2.json
The isolate option doe snot work as expected. It currently prevents all
traffic does is not on the same network. Instead it should only block
traffic between two isolated networks, never external connections.
Also it did not work for ipv6 at all.
Fixes #331
=> rework isolate option to match CNI

src/network/core_utils.rs, test/100-bridge-iptables.bats, test/helpers.bash, test/testfiles/simplebridge.json
When we set a syctl we should not error when they are already set to the
correct value. This allows us to work on a read only /proc when the user
already configured the correct sysctls.
CNI supports this as well.
Fixes #330
=> Support read only /proc

.cirrus.yml
The `c4560539387953152` images were pruned due to a monitoring SNAFU
(fix is in the works).  Luckily the same/similar image is used by
aardvark-dns and is still alive.  Bring that image over here to get
branch-CI working again.
=> Cirrus: Use CI VM images from aardvark

src/commands/setup.rs, src/commands/teardown.rs, src/dns/aardvark.rs, src/firewall/firewalld.rs, src/firewall/iptables.rs, src/firewall/varktables/types.rs, src/network/core.rs, src/network/internal_types.rs, test/100-bridge-iptables.bats, test/200-bridge-firewalld.bats, test/testfiles/dualstack-bridge.json
I've taken a stab at a proof of concept first -- as said in the issue about port 53 shouldn't be used (link below) it seems simple enough to use DNAT for this.
This WIP version has at least two problems:
- I've hardcoded port 1153 as alternative port, we should either use an ephemeral port (problem: we can't know if it's free unless we try to bind to it, so we'd need some retry...) or simpler just make it configurable at network level as a driver-specific option. I'd favor the later.
- I'm not actually checking if dns settings are enabled to create the forward rule, that should obviously be checked.
Is there anything else I missed?
Fixes: https://github.com/containers/aardvark-dns/issues/13
=> dns: start aardvark-dns on a different port

src/dns/aardvark.rs, src/firewall/iptables.rs, src/firewall/varktables/types.rs
While working on #323 I found a few issues, I had intended to just push them together but I found two more today so might as well fix separately.
Individual commit messages have better descriptions, but to recap:
- the chain.create logic in iptables was never correct, we cannot skip creation of the dn chain as it's referred to in unchecked path. That only really matters with next PR as we start doing it all the time but it's also probably possible to pass an empty vec as opposed to None and trigger this today.
- we were trying to delete too many chains, causing chain does not exist errors in teardown when they aren't created in setup
- the logic to cleanup `/run/containers/networks/aardvark-dns/<network>` files was a bit broken, in particular when multiple lines belonged to a container …
=> misc fixes

src/commands/setup.rs
When there are no port mapping we do not have to set the sysctl.
This made it through CI because me merged two PR without rebasing.
=> fix integration read only /proc test

contrib/container_images/Dockerfile.CentOS9, contrib/container_images/Dockerfile.UbuntuLatest, contrib/container_images/Dockerfile.f36
Add the build files for the rust container images to
contrib/container_images.  Build triggers will need to be done in quay
once this PR is commited.  From there, new container images for the rust
builds will be generated at each push to containers/netavark.
=> Add rust container images

.cirrus.yml, contrib/cirrus/setup.sh
Instead of using a packaged version of aardvark-dns, we grabbed the
latest main branch zip copy and use it instead.
=> Use latest aardvark-dns binary

src/dns/aardvark.rs
Netavark now does not double-forks aardvark-dns's server instead it
waits for aardvark-process to return back and success return means
aardvark-dns is ready to serve requests and now forking happens at
aardvark end.
See: https://doc.rust-lang.org/std/process/struct.Command.html#method.spawn
This needs: https://github.com/containers/aardvark-dns/pull/148
Should help in:
* https://github.com/containers/podman/issues/14173
* https://github.com/containers/podman/issues/14171
Alternative to: https://github.com/containers/netavark/pull/300
=> netavark, dns: don't `double-fork` aardvark instead wait for the aardvark process to return.

.cirrus.yml
Fixes: https://cirrus-ci.com/task/5065866822811648
@cevich @Luap99 PTAL
=> Cirrus: cache x86_64 binary for other repos

Cargo.lock, Cargo.toml
This includes an import fix for kernel v5.19, without this it is
impossible to delete interfaces.
Fixes #345
=> update netlink crates

Makefile, docs/Makefile
The Makefile in the docs directory was unable to find the `mandown` binary despite it being in the PATH. Exporting it fixes it.
Also `[[ ... ]]` does not work with `sh`, which `make` uses by default. Using `[ ... ]` works fine.
=> Fix Makefile for docs and main

.cirrus.yml
Contains important updates re: preserving release-branch CI VM images.
Ref: https://github.com/containers/automation_images/pull/157
=> [v1.0.1-rhel] Cirrus: Use the latest imgts container

.cirrus.yml, contrib/cirrus/runner.sh
Other CI systems depend/expect a full set of compiled binaries are
included in the success task's binary artifact (zip file).  However,
it's possible some mistake in CI could silently lead to one or more
binaries not being produced.  For example, a `bin_cache` failure.  Fix
this by verifying all expected/required files are present.  If not,
print the name of the missing binary to assist in
troubleshooting/debugging.
=> Cirrus: Verify expected binary artifacts present

src/commands/setup.rs, src/commands/teardown.rs, src/firewall/firewalld.rs, src/firewall/varktables/types.rs, src/network/bridge.rs, src/network/constants.rs, src/network/core.rs, src/network/core_utils.rs, src/network/driver.rs, src/network/internal_types.rs, src/network/macvlan.rs, src/network/mod.rs, test/100-bridge-iptables.bats, test/200-bridge-firewalld.bats, test/300-macvlan.bats, test/testfiles/internal.json
I am sorry, I know that this is almost impossible to review properly but I couldn't
figure out how to split this out in smaller pieces.
We should abstract the internal driver logic behind a interface. This
makes to code easier to maintain since each driver is isolated.
Also this will allow us much better error handling, in case of errors it
is important to still clean up as much as possible, i.e. when we setup
two networks and the second one fails we should teardown the first as
well.
setup routing sysctl only once
It is enough to only setup the sysctl once.
add test for static mac address
=> create network driver interface

src/error/mod.rs, src/firewall/firewalld.rs, src/firewall/iptables.rs, src/firewall/varktables/types.rs, src/network/bridge.rs, src/network/internal_types.rs
Restructure the types so that we do not need to clone the data.
firewall: PortForwardConfig use IpNet instead of Subnet
We are only interested in a single IpNet so no need to keep the full
Subnet info.
=> firewall types: remove unnecessary clones

Cargo.lock, Cargo.toml, src/dns/aardvark.rs
* We should avoid overriding configs when another instance of aardvark
is trying to commit configs on the same path.
* On certain system a race exists where more than one aardvark instance
are started in the frame where one instance has not yet completed
updating its `aardvark.pid` causing more than one instance to get
started and eventually causing conflits on the requested ports.
Some conditions are reported on `low power hardware which tries to start
a significant amount of containers` and it looks like the case matches with what is described in the second point.
=> aardvark,commit: acquire fs lock when performing commit to avoid `race` across parallel invocations.

contrib/container_images/Dockerfile.CentOS9, contrib/container_images/Dockerfile.UbuntuLatest, contrib/container_images/Dockerfile.f36
For the dhcp proxy which uses the same container images as netavark for
build/test/etc, the protobuf-compiler needs to be added.
=> Add protobuf compiler to container images

Makefile
The vendor tarball generation does not need to check if it's a release
or dev version.
Removal of this check will be especially useful in cases
like #399 where we'll need vendor-tarball generated using HEAD commit
of every PR.
=> Makefile: vendor-tarball remove dev version check

src/firewall/iptables.rs
Signed-off-by: Arthur Sengileyev <arthur.sengileyev@gmail.com>
Seems like a copy-paste typo
=> Fix typo in IPv6 error message

src/commands/setup.rs, src/commands/teardown.rs, src/dns/aardvark.rs, src/network/bridge.rs, src/network/driver.rs, test/100-bridge-iptables.bats, test/200-bridge-firewalld.bats
Based on #369 
The driver already has all information so the aardvark code should not
have to pass it again. This simplifies the code and creates smaller
aardvark config files since it does not duplicate the contianer id and
names just to set more then one ip.
This does not touch the aardvark teardown logic.
Requires https://github.com/containers/aardvark-dns/pull/183
=> rework aardvark setup 

src/network/core.rs, src/network/core_utils.rs
Makes CI validation green again by applying following changes
* clippy: edit expressions that could be replaced by the question mark operator.
* clippy: use if let instead of single match
Ref: https://rust-lang.github.io/rust-clippy/master/index.html#question_mark
Ref: https://rust-lang.github.io/rust-clippy/master/index.html#single_match
=> refactor, clippy: edit syntax as per `clippy` standards

test/100-bridge-iptables.bats, test/200-bridge-firewalld.bats
Retrofit test cases like
* iptables - dual stack dns with alt port
* firewalld - dual stack dns with alt port
have a case where output expects both `A` and `AAAA` record however dig defaults to `A` if nothing is specified hence explicitly request both `A` and `AAAA` records where needed.
Following behaviour is expected after: https://github.com/containers/aardvark-dns/pull/205
Should help with issues seen in: https://github.com/containers/netavark/pull/418
=> tests: dig request both `A` and `AAAA` record for specific cases

.cirrus.yml, contrib/cirrus/runner.sh, contrib/cirrus/setup.sh
In order to prioritize stable CI for upstream development, use VM images with pre-installed rust toolchain and clippy linter.  This prevents these components from changing unexpectedly, especially on new release branches.
Ref: https://github.com/containers/automation_images/pull/214
=> Cirrus: Use images w/ fixed-in-time rust + clippy

build.rs
To make netavark bit by bit reproducible the embedded build date needs to adhere to the SOURCE_DATE_EPOCH standard. So a rebuilder can set SOURCE_DATE_EPOCH to the build binary's build date and reproduce the binary succesfully.
https://reproducible-builds.org/docs/source-date-epoch/
Signed-off-by: Jelle van der Waa <jelle@archlinux.org>
=> Make build date reproducible

src/network/core_utils.rs, test/300-macvlan.bats
When we run container netavark (or in the future the dhcp proxy) should set ip addresses. The ipv6 auto configuration is not wanted in almost all cases so we just disable it for now.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2126243
I was able to reproduce this and can confirm that this fixes the issue for me. I don't think we can test it in CI.
=> Do not use ipv6 autoconf

README.md
Netavark follows github releases which is already listed on homepage. 
* Remove section which needs additional maintenance.
* Follow parity with other projects in github.com/containers such as podman.
Closes: https://github.com/containers/netavark/issues/440
=> README.md: remove latest release section

src/network/bridge.rs, test/100-bridge-iptables.bats
This is a regression. It made its way in made in because the test was not working as expected. The test and code is now fixed. An internal network should never have an default gateway since it cannot reach outside anyway.
Fixes #415
=> bridge: do not set gateway for internal network

src/commands/setup.rs, src/error/mod.rs, src/firewall/firewalld.rs, src/firewall/mod.rs, src/network/bridge.rs, src/network/core_utils.rs, src/network/macvlan.rs, src/network/netlink.rs
Instead of using two function for types String and str we can just use a generic which implements Into<String>. This allows us to only use one function for both.
=> error: NetavarkError use Into<String> Trait

src/network/netlink.rs, src/test/netlink.rs
It is not required for netavark since we just delete links on teardown but the dhcp proxy might need to remove addresses and/or routes when it gets a new lease.
Unfortunately the del_route unit test doe snot seem to work since it requires "real" working routes which we cannot create in a custom netns.
=> netlink: add del_{addr,route} calls

src/commands/setup.rs, src/commands/teardown.rs, src/dns/aardvark.rs, src/network/bridge.rs, src/network/driver.rs, src/network/types.rs, test/100-bridge-iptables.bats, test/testfiles/dualstack-bridge-custom-dns-server.json
Netavark now accepts `dns_servers` as part of `NetworkOptions` which contains list of comma seperated custom DNS servers for containers. Aardvark-dns will use these as resolver for a specific container instead of host's default resolver.
Implements feature here and needs: https://github.com/containers/aardvark-dns/pull/240
=> netavark ,aardvark: accept and populate custom `dns_servers` for containers

Makefile
The EL spec files have a `v` for version in front of the numberic version.  Easier to just fix in the Makefile.
=> Add 'v' to tarball names

src/commands/setup.rs, src/commands/teardown.rs, src/main.rs, src/network/mod.rs, src/test/test.rs, test/001-basic.bats
There is no need to open /dev/stdin, we should just read directly from fd 0 without having to call open().
Also convert the error inside the function to prevent duplication.
=> NetworkOptions::load(): do not open /dev/stdin

src/network/netlink.rs
* netlink: improve error message on invalid netlink result
While unlikely when netlink returns something unexpected we should
provide more details so we know where it failed. This will most likely
only fail when we called something incorrectly or due a kernel bug.
If it run with trace log level we already display the raw netlink
messages so that should be enough info to start debugging.
* netlink: check sequence_number
Make sure we only parse messages that are for us. If the sequence_number
does not match it likely means we screwed up somewhere. Better to catch
this early than having the callers get unexpected responses which causes
hard to debug issues.
=> netlink: better errors on invalid querys

src/network/macvlan.rs, src/network/netlink.rs, test/300-macvlan.bats
When the container interface and host interface use the same link netavark fails with EEXISTS. This is a weird kernel behavior because we directly create the interface in the netns but the kernel still checks in the host ns and thus it will fail if the same name is already used there.
To fix this we need to create the interface with a tmp name then rename it in the netns. For performance reason we still try the quick way first and only fallback to tmp name if required.
=> macvlan: fix name collision on hostns

src/network/netlink.rs, test/100-bridge-iptables.bats
Right now getting a Permission denied error is not very helpful for users if adding an ipv6 addr fails because they have ipv6 disabled in the kernel. We should wrap that error and provide a hint about disabled ipv6 support in the kernel.
Fixes #439
=> netlink: return better error if ipv6 is disabled

test/100-bridge-iptables.bats, test/testfiles/dualstack-bridge-multiple-custom-dns-server.json
Unskip tests which was added here: https://github.com/containers/netavark/pull/452 but was skipped temporarily. 
* tests: unskip existing test for custom dns server
* tests: add test for verifying multiple custom dns severs
- Add test in netavark to verify if it generates correct aardvark config
when multiple custom dns servers are specified in `NetworkOptions`.
=> test: unskip exisiting `custom_dns_server` tests and add a new one.

Cargo.lock, Cargo.toml
Removes chrono as a library dependency, since it wasn't being used anywhere, and reduces the features used by the build dependency to avoid bringing in time 0.1
=> Drop indirect dependency on time 0.1

src/network/bridge.rs, src/network/constants.rs, src/network/core_utils.rs, src/network/macvlan.rs, src/network/netlink.rs, src/test/netlink.rs, test/100-bridge-iptables.bats, test/testfiles/metric.json
Metrics allow us to specify which default route will be preferred when a container connects to multiple networks. By default, all routes will get a metric of 100. If two routes go to the same location (e.g. multiple default routes, one for each network, as Netavark does by default), the kernel by default round-robins traffic between all of them, but if the metrics for the routes differ, the route(s) with the lowest metric are chosen.
For confusing reasons, metric is actually called preference in Netlink - and, doubly confusing, there is also a "metrics" option for routes in Netlink as well. Which, naturally, is completely unrelated to route metric. Sigh.
=> Add support for route metrics

src/network/macvlan.rs, test/300-macvlan.bats
If the interface name is already used in the netns the rename call will fail and netavark error out. This is correct but before it returns it should remove the tmp interface otherwise we end up leaking it.
=> macvlan: remove tmp interface when name already used in netns

src/network/constants.rs, src/network/core_utils.rs
Fixes a small TODO in the code. Also improve the error message including "io error" make no sense. I also added the actual mode name in the error.
=> macvlan modes: use upstream consts

.github/workflows/rerun_cirrus_cron.yml
Also update the regular cirrus-cron checking job to reuse workflow from podman instead of buildah.
=> [skip-ci] GHA: Add cirrus-cron rerun job

src/firewall/iptables.rs, src/network/bridge.rs, test/100-bridge-iptables.bats, test/testfiles/two-networks.json
Only on a complete teardown we should remove the network forwarding rules.
Fixes #491
=> fix iptables teardown

src/dns/aardvark.rs, src/error/mod.rs, src/firewall/firewalld.rs, src/firewall/iptables.rs, src/firewall/mod.rs, src/network/bridge.rs, src/network/constants.rs, src/network/internal_types.rs, src/network/types.rs
Rust doc comments need three slashes[1]. Using just `//` makes rust think they are a normal comment which should not be included in the API docs. This is important if you use function highlighting in my IDE for example.
[1] https://doc.rust-lang.org/reference/comments.html
=> fix rust doc comments

src/commands/setup.rs, src/commands/teardown.rs, src/dns/aardvark.rs, src/firewall/iptables.rs, src/firewall/varktables/types.rs
In many places we really do not need to clone the values and can just use references with lifetimes.
I also removed the mut declaration in the aardvark interface which is not needed and thus just causes confusion.
There is a lot more I could do but these ones were very simple to fix and I don't want to spend more time on this right now.
=> remove number of .clone() calls

src/dns/aardvark.rs, src/network/bridge.rs, src/network/types.rs, test/100-bridge-iptables.bats, test/testfiles/dualstack-bridge-network-container-dns-server.json
Aardvark and podman supports `network_dns_servers` which allows aardvark to configure a resolver at network level and all containers attached to a network honors this resolver.
Needs: https://github.com/containers/aardvark-dns/pull/252
=> aardvark, netavark: support network scoped dns via `network_dns_servers`

src/commands/setup.rs, src/commands/teardown.rs, src/network/driver.rs
Add the ns_path to setup and teardown commands.  This is needed for DHCP macvlan.
=> Add nspath to commands

build.rs
chrono has deprecated from_timestamp in favor of from_timestamp_opt. this PR allows for new versions of chrono to be used.
Fixes #484
=> chrono: use from_timestamp_opt

.cirrus.yml, contrib/cirrus/runner.sh
We removed vendoring a long time ago, therefore we do not need this check. I just saw it fail on one of my PRs because of a CI problem.
=> remove verify_vendor CI task

src/commands/mod.rs, src/commands/setup.rs, src/commands/teardown.rs, src/commands/update.rs, src/dns/aardvark.rs, src/main.rs, src/network/core_utils.rs, test/100-bridge-iptables.bats
Netavark update allows container managers to update network scoped DNS servers of any configured network and notify running `aarvark-dns` about it.
```console
netavark-update
Updates network dns servers for an already configured network
USAGE:
netavark update --network-dns-servers <NETWORK_DNS_SERVERS> <NETWORK_NAME>
ARGS:
<NETWORK_NAME>    Network name to update
OPTIONS:
-h, --help                                         Print help information
-n, --network-dns-servers <NETWORK_DNS_SERVERS>    DNS Servers to update for the network
```
=> update: add support for `netavark update` command

Makefile, docs/publish-crate.md
* Add new rule `make crate-publish` to automate publish at https://crates.io/crates/netavark
* Document steps for publishing to `crates.io`
=> release,make: add rule `make crate-publish` for publishing crates.io

Cargo.lock
crossbeam-utils 0.8.13 is yanked
https://crates.io/crates/crossbeam-utils/0.8.13.
Stop using it yanked version so Cargo does not warns us in the next release.
Ref: https://crates.io/crates/crossbeam-utils/versions
Closes: https://github.com/containers/netavark/issues/521
=> Cargo.lock: stop using yanked `0.8.13` crossbeam-utils and bump to `0.8.14`

src/commands/setup.rs, src/commands/teardown.rs, src/commands/update.rs, src/main.rs
Generally ownership transfer by passing `String` parameters is unidiomatic.  By passing the config dir as a borrowed `&str` we avoid the need to heap allocate a copy of the string `/tmp`.
(No particular motivation, I just happened to be looking
at this code)
Signed-off-by: Colin Walters <walters@verbum.org>
=> main: Pass config_dir as `&str`

Makefile, contrib/cirrus/runner.sh, docs/Makefile
Regression caused by 011f899919c9. We only want to build actual man pages of course and not general docs.
This commit fixes the wildcard target to only use the `.1.md` files instead of all markdown files.
Also add the step to the validate target to make sure CI tests this target.
Fixes #524
=> fix make docs

contrib/cirrus/setup.sh
Fixes: https://github.com/containers/netavark/pull/518
See also: https://github.com/containers/aardvark-dns/pull/269
Around the time of this commit, a bug was discovered (the hard way) in Cirrus-CI:  If a `[skip-ci]` build merges, it will be marked successful but not publish any artifacts via the "latest" permalink. Since netavark and aardvark depend on each other's latest binaries, this can lead to a chicken-and-egg problem.
While the underlying Cirrus-CI bug has now been fixed, this is still a fragile situation for CI.  At the same time, it's beneficial to developers for CI runs to happen as quickly as possible.  Meaning, CI should try to avoid compiling when possible.
Resolve both issues by attempting to download from the permalink, but if that fails, fallback to compiling and building …
=> Cirrus: Add backup to aardvark-binary artifact DL

.cirrus.yml, Cargo.lock, Cargo.toml, Makefile, src/network/core_utils.rs, src/network/internal_types.rs, src/network/macvlan.rs, src/network/macvlan_dhcp.rs, src/network/mod.rs, test/testfiles/macvlan-dhcp.json
We can now support DHCP macvlan use cases for setup.  Added plumbing for additional arguments requeired as well, such as container mac address, etc.
Test forthcoming when teardown is complete.
=> Add ability for MacVLAN dhcp

src/network/constants.rs, src/network/core_utils.rs, src/network/driver.rs, src/network/mod.rs, src/network/vlan.rs, test/400-ipvlan.bats, test/testfiles/ipvlan-internal.json, test/testfiles/ipvlan-mtu.json, test/testfiles/ipvlan.json
Status:
- it compiles and there are integration tests which pass
- I tested this with podman and was able to ping the container from another physical device on the network.
- This is a ton of copy&paste because macvlan and ipvlan are so similar, we might want to reduce that. Let's discuss this.
- `get_default_route_interface` should be easy to move to e.g. core_utils
- `setup` could be moved bei either using generics or by passing `CreateLinkOptions` as an argument
- the integration tests could completely move to generated testfiles to we can use a variable for the driver name
=> add ipvlan support

Cargo.lock, src/network/macvlan_dhcp.rs
The const for default the netavark dhcp proxy UDS path was changed to a different module in its project. This is required to continue to build against newer versions of the proxy.
=> Fix UDS path

.cirrus.yml, contrib/cirrus/cache_groom.sh, contrib/cirrus/lib.sh
Prior to this commit, the cache maintained for the main branch has grown
to over 16gigabytes.  Attempts to upload it are causing frequent branch-
level CI failures due to being larger than the maximum allowable.
Attempt to fix this by introducing a cache-grooming script and altering
the cache-keys to track with dependency specification and build settings.
Content for the grooming script comes mainly from three places:
1. [Cargo documentation](https://doc.rust-lang.org/nightly/cargo/guide/build-cache.html)
2. The rust-cache github action [(typescript) source code](https://github.com/Swatinem/rust-cache/tree/master/src)
3. This [cargo home in CI section](https://doc.rust-lang.org/nightly/cargo/guide/cargo-home.html#caching-the-cargo-home-in-ci)
For branch-level cache, the grooming script …
=> Cirrus: Improve caching effectiveness

src/network/bridge.rs, src/network/netlink.rs, src/network/vlan.rs
To make the code base more inclusive, I've changed a few variable names from "master*" to "primary*".
[NO NEW TESTS NEEDED]
Signed-off-by: tomsweeneyredhat <tsweeney@redhat.com>
=> Convert a few words to more inclusive ones

Cargo.toml, Makefile
See https://github.com/coreos/cargo-vendor-filterer/issues/50 This fixes an error trying to vendor for m68k.
Also while we have the patient open, move the platform list to `Cargo.toml` in declarative format.
=> Switch to explicit platform list for `cargo vendor-filterer`

Cargo.lock, Cargo.toml, RELEASE_NOTES.md
* removed crossbeam-utils
* dependency updates
* preliminary macvlan dhcp support (not fully supported yet)
* addition of ipvlan support
=> Releasev1.5.0

.cirrus.yml
Cirrus-CI sandboxes container-based tasks that request 4 or more CPUs within the community-cluster.  Depending on cluster load, this can result in heavy-CPU bound tasks being queued for an extended period of time - or even timing out all together.
Since the `ubuntu_20` and `centos9` tasks are only checking buildability, reduce their requested CPUs so they can finish more reliably in relation to all the other VM-based tasks.  This matches settings already in place for similar tasks in the aardvark-dns repo.
=> Cirrus: Reduce requested CPUs for compile-tasks

.packit.sh, .packit.yaml, netavark.spec.rpkg
This commit will run COPR builds on every PR against all active
releases of CentOS Stream and Fedora, thus allowing buildability checks before the
PR merges.
Builds are done on a custom COPR project:
`rhcontainerbot/packit-builds`.
Ref: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/packit-builds/
The build targets are set in the copr itself, so we don't need to
explicitly mention them in `.packit.yaml`, making upstream configuration
a lot simpler.
The `spec.rpkg` file meant for rpm builds post-pr-merge at
`rhcontainerbot/podman-next` copr gets reused for packit builds, so the
packit jobs are independent of Fedora / CentOS dist-git.
=> Packit: initial enablement

src/firewall/fwnone.rs, src/firewall/mod.rs, test/500-bridge-fwnone.bats
Passing environment valuepair NETAVARK_FW=none disables all firewall/portmapper related features leaving configuration of firewall to user.
=> Support none parameter on NETAVARK_FW

test/100-bridge-iptables.bats
The variable is called fw_driver, the typo resulted in the driver name missing. Not a issue but it looks odd in the test logs.
=> fix default route metric test name

.packit.sh
.packit.sh was searching for the wrong release string and as a result not replacing anything, resulting in all packit builds ending up with release tag `1`.
Ref: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/packit-builds/package/netavark/
This commit will correctly update the release tag.
=> packit: Update build release tag correctly

test/helpers.bash
I am not not 100% sure because I was unable to reproduce even with
hack/get_ci_vm.sh. This flakes permanently in CI so there must be a
different in the environment which causes it.
However looking at the code we spawn the nc listener in the background
so there is no guarantee that it will already listen when we make the nc
connect call. To fix this we use the wait_for_port logic to ensure the
port is bound.
For now there is no sctp support, the /proc file format for it is
completely different and I didn't want to spend more time on it so I
just added a sleep and call it good enough.
Fixes #433
=> fix aarch64 ncat flake

Cargo.lock, Cargo.toml, src/dhcp_proxy/dhcp_service.rs, src/dhcp_proxy/proxy_conf.rs, src/dhcp_proxy_server/server.rs
A fixes for the breaking changes:
- timeout is u32
- DhcpV4Config::new_proxy() no longer return an Result type
This also fixes the build issue on i686.
Fixes #578
=> update to mozim 0.2.1

src/commands/update.rs, test/100-bridge-iptables.bats
`podman network update test --dns-drop 8.8.8.8` converges to a case when there are no nameservers for a network and netavark handles it correctly here: https://github.com/containers/netavark/blob/main/src/dns/aardvark.rs#L366
So allow users to update exisiting network with empty list of `network_dns_servers`
=> update: should allow empty `network_dns_servers`

Makefile, netavark.spec.rpkg
Currently, the COPR package does not include the Systemd unit files under `contrib/systemd/system`, which are desirable for use with the new DHCP proxy functionality. This PR adds these unit files to the COPR RPM package file, as well as the Makefile install and uninstall tasks.
=> Include Systemd Unit Files in RPM Package

.cirrus.yml
[There's a clash w/ the x86_64 binary `netavark-dhcp-proxy`](https://cirrus-ci.com/task/5061451941937152):
```
unzip armbinary.zip
+ unzip armbinary.zip
Archive:  armbinary.zip
replace bin/netavark-dhcp-proxy? [y]es, [n]o, [A]ll, [N]one, [r]ename:
NULL
(EOF or read error, treating as "[N]one" ...)
```
Rather than hard-code every new binary file, simply rename them all in a loop.
=> Cirrus: Fix success failing on artifact extraction

src/firewall/varktables/helpers.rs
We should only log that the rule exists when this is the case. I noticed this while debugging #641.
=> iptables: fix incorrect debug statement

Cargo.toml, src/commands/dhcp_proxy.rs, src/dhcp_proxy/dhcp_service.rs, src/dhcp_proxy/lib.rs, src/proto/proxy.proto
Attention:
This is a rebase of
https://github.com/containers/netavark-dhcp-proxy/pull/61 which was written by Jack Baude. Jack is tied up in school and I simply performed the rebase to netavark after ithe netavark and netavark-dhcp-proxy projects were merged.
In the case where a client asks the proxy server for a leased address, it is possible that the client would quit (hangup) before the server could respond.  Or more likely, the server is having difficulty obtaining a lease and the client quits.  In either case, when the client quits, the server needs to stop trying to aquire a lease.
* start using mozim 0.2.1 with async lease capabilities.
* fixed timeout type to match mozim 0.2.1
* detect client disconnection with tokio oneshot channel
* use async lease DORA
=> Quit Leasing when Client disconnects

Makefile, README.md, examples/error-plugin.rs, examples/host-device-plugin.rs, examples/stderr-plugin.rs, plugin-API.md, src/commands/setup.rs, src/commands/teardown.rs, src/error/mod.rs, src/lib.rs, src/main.rs, src/network/driver.rs, src/network/mod.rs, src/network/netlink.rs, src/network/plugin.rs, src/network/types.rs, src/plugin.rs, src/test/netlink.rs, test/500-plugin.bats
Add a plugin system for netavark,
check the plugin-API.md file for a description.
see commits for details
=> add netavark plugin support

src/dhcp_proxy/lib.rs, src/dhcp_proxy_client/client.rs, src/dhcp_proxy_client/commands/setup.rs, src/dhcp_proxy_client/commands/teardown.rs, src/error/mod.rs
Wrap the tonic status errors in the netavark error type, this allows us to create better error messages.
Also a bit complicated but special case when the socket is not found and return a message to consider enabling the netavark-dhcp-proxy.socket. old error:
`unable to obtain lease: status: Internal, message: "transport error", details: [], metadata: MetadataMap { headers: {} }` new error:
`unable to obtain lease: socket "/run/podman/nv-proxy.sock": No such file or directory (os error 2), is the netavark-dhcp-proxy.socket enabled?`
=> dhcp-proxy: use better error when connection fails

src/commands/dhcp_proxy.rs
The flag was spelled incorrectly, lets fix this before the release.
=> dhcp-proxy: fix typo for --activity-timeout

Cargo.lock, Cargo.toml, RELEASE_NOTES.md
* Now supports a driver plugin module for user defined network drivers
* Initial MACVLAN DHCP support (additional unit file required for packagers)
* Dependency updates
=> Releasev1.6.0

Cargo.lock, Cargo.toml, src/commands/setup.rs, src/commands/teardown.rs, src/commands/update.rs, src/dhcp_proxy_client/client.rs, src/dhcp_proxy_client/commands/setup.rs, src/dhcp_proxy_client/commands/teardown.rs, test-dhcp/helpers.bash
`forbid_empty_values` was replaced with `builder::NonEmptyStringValueParser`. Also fixes the awkward command structure for the proxy client which required an extra argument despite not using it.
=> update clap to v4

src/dns/aardvark.rs, test/100-bridge-iptables.bats
`network update` maybe called by podman when no container is running in such case no aardvark config is present so netavark must return as-in without throwing error since podman database is still updated.
Closes:
BZ 2188524
BZ 2182898
=> aardvark,network-update: no error when aardvark config is not there

src/commands/teardown.rs, src/commands/update.rs, src/dns/aardvark.rs
Ed reported a flake in podman where aardvark-dns pid was not found hen we tried to stop it. It is not clear why but the error report is far from optimal, we should never throw away the original error context. This is very important to understand what is going on.
Port most over to our netavark error type and wrap where needed. Also change the pid type to pid_t. It is i32 so it did not cause any issues before but this makes it more obvious that we have the correct type.
[1] https://github.com/containers/podman/issues/18325
=> aardvark-dns pid: return better errors

Makefile
the crate publish target had a small typo where it was comparing versions.  one of the versions always had a prefix of v.
=> correct typo in Makefile

src/network/bridge.rs, src/network/core_utils.rs, src/network/internal_types.rs, src/network/types.rs, src/network/vlan.rs, test/100-bridge-iptables.bats, test/200-bridge-firewalld.bats, test/300-macvlan.bats, test/400-ipvlan.bats, test/testfiles/bridge-nogateway.json, test/testfiles/bridge-staticroutes.json, test/testfiles/ipv6-bridge-staticroutes.json, test/testfiles/ipvlan-nogateway.json, test/testfiles/ipvlan-staticroutes.json, test/testfiles/macvlan-nogateway.json, test/testfiles/macvlan-staticroutes.json
This PR adds the ability to configure static routes. Discussion is in #678 
Supports both ipv4 and ipv6 routes including optional route metric. 
Example json:
```
"network_info": {
"podman": {
"dns_enabled": false,
"driver": "bridge",
"id": "53ce4390f2adb1681eb1a90ec8b48c49c015e0a8d336c197637e7f65e365fa9e",
"internal": false,
"ipv6_enabled": false,
"name": "podman",
"network_interface": "podman0",
"subnets": [
{
"gateway": "10.88.0.1",
"subnet": "10.88.0.0/16"
}
],
"routes": [
{
"destination": "10.89.0.0/24",
"gateway": "10.88.0.2",
"metric": "120"
},
{
"destination": "10.90.0.0/24",
"gateway": "10.88.0.3"
}
]
}
}
```
=> Static routes

src/dns/aardvark.rs, test/100-bridge-iptables.bats
`network update` maybe called by podman when no container is running in such case no aardvark config is present so netavark must return as-in without throwing error since podman database is still updated.
Closes: **BZ#2188566**
Closes: **BZ#2188524**
Closes: **BZ#2182898**
Closes: **BZ#2188340**
Backport of: https://github.com/containers/netavark/pull/677
=> [release-v1.5.0] aardvark: no error when aardvark config is not there

src/network/bridge.rs, src/network/constants.rs, src/network/vlan.rs, test/100-bridge-iptables.bats, test/200-bridge-firewalld.bats, test/300-macvlan.bats, test/400-ipvlan.bats, test/testfiles/bridge-nodefaultroute.json, test/testfiles/ipvlan-nodefaultroute.json, test/testfiles/macvlan-nodefaultroute.json
This PR adds the option to enable no_default_gateway in the options map. The result is that netavark will not add default routes to the network namespace.
This fixes the issue that DNS would not work in containers/common#1440 when using no_auto_gateway. The solution is to use this new no_default_gateway instead of no_auto_gateway.
=> add no_default_gateway option

Cargo.lock, Cargo.toml, src/network/bridge.rs, src/network/constants.rs, src/network/core_utils.rs, src/network/vlan.rs
Expose the netlink IFLA_MACVLAN_BC_CUTOFF option as bclim like the ip
command does. We still need c/common and podman patches to allow this
option for podman network create.
Also I created a PR[1] upstream in the netlink lib to allow setting
these options directly instead of using the DefaultNla work around as I
do here.
TODO: Add a test but for now this option is not in a released version of
iproute so there is no way to check for it right now.
[1] https://github.com/rust-netlink/netlink-packet-route/pull/32
This is needed for https://bugzilla.redhat.com/show_bug.cgi?id=2183896
=> macvlan: add bclim option

Cargo.lock, Cargo.toml
Minor release for RHEL.
bclim option (https://github.com/containers/netavark/pull/699):
https://bugzilla.redhat.com/show_bug.cgi?id=2210111
https://bugzilla.redhat.com/show_bug.cgi?id=2210113
--dns-add no error without container (https://github.com/containers/netavark/pull/681):
https://bugzilla.redhat.com/show_bug.cgi?id=2210118
https://bugzilla.redhat.com/show_bug.cgi?id=2210117
=> Bump to v1.5.1

src/firewall/varktables/types.rs, src/network/bridge.rs, src/network/constants.rs, src/network/internal_types.rs, test/100-bridge-iptables.bats, test/testfiles/isolate3.json, test/testfiles/isolate4.json
Currently, it appears that isolation is only enabled when both bridges are in isolate mode.  
This means that communication with networks that do not have isolate enabled is still possible.
What about using `isolate=strict` to deny communication with networks that do not have isolate enabled?  
Specifically, add a new chain of iptables and add a DROP rule to the chain for networks that do not have isolate enabled.
Here is a table showing the connectivity between networks before and after this change:
before:
```
|send\recv  |nonisol1   |nonisol1   |isol1      |isol2      |
|-----------|-----------|-----------|-----------|-----------|
|nonisol1   |     o     |     o     |     o     |     o     |
|nonisol2   |     o     |     o     |     o     |     o     |
|isol1      |     o     |     o …
```
=> feature: isolation among all netavark bridge 

src/commands/setup.rs, src/commands/teardown.rs, src/commands/update.rs, src/dns/aardvark.rs, src/main.rs, test/100-bridge-iptables.bats, test/200-bridge-firewalld.bats, test/helpers.bash
Using /tmp as default makes no sense, all callers that need dns should give us a proper path. Podman already does this so it should not cause any backwards compat problems.
I had to change the teardown logic a bit as we first need to confirm if we have network with dns before we should check if --config was given.
Also rework tests to always set --config to avoid code duplication.
=> netavark: make --config required for dns

Cargo.lock, Cargo.toml
Edition 2021 was added in rust v1.56.0, we already depend on newer rust
versions to build so we should be able to bump this without issues.
Also run cargo update and update tonic-build which needs the 2021 edition (https://github.com/containers/netavark/pull/662)
=> bump rust edition to 2021 and update deps

rpm/netavark.spec
The lowercase `and` in the License field isn't compatible with spdx license format.
This commit replaces all `and` with `AND` in the License field in spec.
[NO NEW TESTS NEEDED]
=> [CI:BUILD] rpm: spdx compatible license field

README.md
Without `protoc` installed, the `make` command fails looking for it.
=> Add protoc dependency to README

.gitignore, src/firewall/firewalld.rs, src/firewall/fwnone.rs, src/firewall/iptables.rs, src/firewall/mod.rs, src/firewall/varktables/types.rs, src/network/bridge.rs, src/network/internal_types.rs, test/100-bridge-iptables.bats
When running container in non default podman network with dns enabled and default INPUT host firewall policy is DROP, name resolution does not work in container. To fix this, a firewall rule to allow dns traffic was added. 
Signed-off-by: Chetan Giradkar <cgiradka@redhat.com>
=> Add ACCEPT rule in firewall for bridge network with internal dns

Cargo.lock, Cargo.toml, src/network/core_utils.rs
The nix crate removes all features by default so we need to explicitly list what we use.
Second, the io API's changed and all use the AsFd trait now. This is great for IO safety but will require larger changes to migrate from RawFd. Thus I went the easy way and use unsafe (not really unsafe here) and construct and a new File object (which impl AsFd) for the setns call.
=> bump nix to 0.27.1

examples/host-device-plugin.rs, src/commands/setup.rs, src/commands/teardown.rs, src/network/bridge.rs, src/network/core_utils.rs, src/network/driver.rs, src/network/netlink.rs, src/network/vlan.rs
This is much safer because we no longer pass a single int around. With BorrowedFd<> the compiler will actually make sure the underlying file will not be closed before we use it.
I could have made every struct generic to accept the AsFd trait but that would have resulted in IMO more complex code without benefit.
Fixes #806
=> rust io safety: convert RawFd to BorrowedFd<>

README.md
This header no longer exists so we should not link to it, the top level page is just fine.
=> fix podman.io community link

Cargo.toml
Newer cargo-vendor-filterer allows us to avoid enumerating the full matrix of (architecture, gnu|musl) here.
=> build-sys: Filter to tier 2 Linux declaratively

contrib/container_images/Dockerfile.Fedora, contrib/container_images/Dockerfile.UbuntuLatest
We need 1.67 and ubuntu:latest (which tracks LTS) still does not have it and there have been no updates to the image in 20 or more days.  Change from latest to rolling.
Update from fedora 38 to 39 and rename the Containerfile to exclude the fedora version.
when this PR merges, we need to update quay.io for the Fedora build.
=> Update rust container build files

Cargo.lock, Cargo.toml, Makefile, contrib/systemd/system/netavark-firewalld-reload.service.in, rpm/netavark.spec, src/commands/firewalld_reload.rs, src/commands/mod.rs, src/commands/setup.rs, src/commands/teardown.rs, src/commands/update.rs, src/firewall/firewalld.rs, src/firewall/fwnone.rs, src/firewall/iptables.rs, src/firewall/mod.rs, src/firewall/state.rs, src/main.rs, src/network/bridge.rs, src/network/constants.rs, src/network/driver.rs, src/network/internal_types.rs, src/network/types.rs, test/100-bridge-iptables.bats, test/200-bridge-firewalld.bats, test/helpers.bash
Add a new service command which listens on for the firewalld reload dbus event and then re-adds all firewall rules back.
The unit file is written so that it is only started and stopped with firewalld so it never runs unless needed. The new unit is called netavark-firewalld-reload.service.
Tests have been added to ensure it is working as expected.
This required more changes that I would have liked but it is important to only write the minimal firewall config to disk to not waste memory as the config dir is on tmpfs.
Fixes https://issues.redhat.com/browse/RHEL-3079
=> Add firewalld reload service

src/firewall/state.rs, src/network/bridge.rs, test/100-bridge-iptables.bats
There is a small possibility that the reload service could add fw rules after the container was teardown and thus leak them forever.
Consider this case if both processes run in parallel:
| netavark fw reload service  |  netavark teardown |
|-----------------------------|--------------------|
| read fw config              |                    |
|                             | remove fw config   |
|                             | remove fw rules    |
| add fw rules                |                    |
In order to prevent the race, this commit adds a lock file to ensure that it is not possible to add/remove fw configs while the reload service is doing it's thing.
=> firewalld-reload: prevent race which could leak fw rules

src/commands/firewalld_reload.rs, src/commands/mod.rs, src/commands/setup.rs, src/commands/teardown.rs, src/commands/update.rs, src/dns/aardvark.rs, src/firewall/state.rs, src/main.rs, src/network/driver.rs, src/network/mod.rs, src/test/test.rs, test/001-basic.bats
Rust String type has a pretty well documented difference to most string types in many other languages. A rust string must be valid utf-8. However linux itself does not care about the char encoding in paths, it is simply a non zero byte array. This means that technically netavark will not accept all valid paths. While it unlikely that anyone is using non utf-8 paths in the real world it is still a non great to deny that.
Rust actually offers the OsString/OsStr types that do not enforce the utf-8 requirement. And there is also PathBuf/Path types that futher abstract file paths. So to fix this just use these types instead.
See the added test which checks for it, without this patch we would see a `error: invalid UTF-8 was detected in one or more arguments` message.
=> use OsString/Path over String for file paths

test/helpers.bash
firewalld_reload var needs to be defined.
This fixes the superfluous error message:
`helpers.bash: line 541: [: =: unary operator expected` which can be seen in the logs on failures.
Fixes b5d7510039 ("firewalld-reload: add integration tests")
=> test: fix syntax problem in helpers.bash

Cargo.lock, Cargo.toml, src/dhcp_proxy/lib.rs
With http-1.0.0, the use of HTTP::Uri is no longer valid for when a tonic::transport::Uri is required.
=> Use tonic::transport::Uri instead of HTTP

Cargo.lock, Cargo.toml, src/error/mod.rs, src/firewall/firewalld.rs, src/firewall/iptables.rs, src/firewall/mod.rs, src/firewall/nft.rs, src/firewall/state.rs, src/network/bridge.rs, src/network/internal_types.rs, test/250-bridge-nftables.bats
This implementation lacks isolation support at present (that'll be a followon PR) and has only very minimal testing at the moment (including absolutely 0 testing for IPv6), but does handle all core tasks including forwarding and all types of port forwarding.
Fixes #816
=> Initial draft of nftables support

Cargo.lock, Cargo.toml
Instead of vendoring by tag (~ a year old), grab the latest commit. This gets us a number of schema changes that are necessary to safely decode all possible JSON generated by nftables.
Solved an issue I ran into during demos today.
=> Bump nftables-rs to latest commit

src/firewall/nft.rs, src/firewall/varktables/types.rs, src/network/bridge.rs, src/network/internal_types.rs, test/250-bridge-nftables.bats, test/testfiles/isolate1.json
Replicates the current iptables approach (3 isolation chains, with support for strict and normal isolation, or no isolation at all). No significant changes from iptables implementation.
=> Add support for isolation to the nftables driver

DISTRO_PACKAGE.md
Given there's a vendored tarball as part of releases, does this mean this is preferred over vendoring at build time `cargo update && cargo vendor` before building?
Signed-off-by: Danish Prakash <danish.prakash@suse.com>
=> DISTRO_PACKAGE: fix incorrect vendored tar archive URL

.packit.yaml, rpm/netavark.spec
Bodhi tasks are disabled in Packit config to allow manual submission of a single bodhi update containing netavark and aardvark-dns X.Y builds.
The netavark rpm will now depend on the minimum aardvark-dns X.Y build available to also account for patch releases. Ref: https://github.com/containers/netavark/issues/907#issuecomment-1914504620
Resolves: #907
=> [CI:BUILD] Packit/rpm: fix aardvark-dns handling

src/dns/aardvark.rs, test/100-bridge-iptables.bats
Update is not required to be in the same network namespace as everything else, because we're just restarting an existing server with an updated config. Make the check for Aardvark's netns only happen if we are not updating as such.
Fixes #911
=> Do not perform network namespace detection on AV update

src/dns/aardvark.rs, test/100-bridge-iptables.bats
While commit 45f158118d fixed one problem it added another one as well. The condition of !is_update got mixed up and now never returned in the good case thus the code went to the end of the function and started a new aardvark-dns conflicting with an existing running arrdvark-dns.
=> fix netavark update to not start a new aardvark-dns

perf-netavark.sh
Fix the missing required --config arg for netavark and make the first argument of the script the fw driver. This allows quickly testing some basic performance of the fw driver.
=> perf-netavark: fix missing --config + add fw driver arg

src/dns/aardvark.rs
Right now there is a race condition where we return errors even in cases where they should be ignored. When we send SIGHUP to aardvark on teardown it might exit when all containers are removed. This means the check afterwards might read the netns path at a weird time while the process is being removed from the kernel structures. I assumed the only error can be ENOENT but I was wrong, in CI we also see EACCES and in my reproducer I also saw ESRCH. Given the check is a nice to have do ignore all errors there.
Fixes containers/podman#22103
=> fix aardvark-dns netns check

Cargo.lock, Cargo.toml, src/firewall/nft.rs
This contains some breaking changes to the payload type[1] so fix them.
[1] https://github.com/namib-project/nftables-rs/commit/0deaf7d86429b79b857a25f3cd1fb7fdeef8b056
nftables: only dump netavark table rules
This makes things easier as we the lib no longer needs to parse
unrelated rules, we only need to touch/care about the netavark table.
One big issue is that the rust nftables lib is not feature complete and
all rules that it doesn't undersatnd cause the json deserialization to
fail hard and thus easily break netavark. With this fix we only dump our
rules and because we the rules via this lib we should never encounter
unspported rules and thus it should always work.
I assume this also results in a nice speed up if there are many rules in
other tables on the host as they will never be …
=> update to nftables 0.4 and only read netavark table rules

src/network/bridge.rs, test/100-bridge-iptables.bats, test/250-bridge-nftables.bats, test/testfiles/two-networks.json
As it turns out our routing setup doesn't play nice with strict Reverse Path Forwarding. The issue is that the incoming packages are routed in via one bridge but may be routed out from the container via another bridge and thus get dropped by strict filtering. The fix is simple, set the filter to loose mode.
From the sysctl doc:
If using asymmetric routing or other complicated routing,
then loose mode is recommended.
This applies to us so it seems like the proper fix. Added tests to ensure it works.
Fixes https://issues.redhat.com/browse/RHEL-32500
=> fix port forward with strict RPF and multi networks

.packit.yaml
Include a distinct value for the packages key for rhel copr_build jobs to avoid packit status reporting issues.
=> [skip-ci] Packit: distinct `-rhel` packages value

.cirrus.yml, src/dhcp_proxy/ip.rs, src/dhcp_proxy/lib.rs, src/dhcp_proxy/types.rs, src/dns/aardvark.rs, src/network/macvlan_dhcp.rs, src/network/vlan.rs, test/helpers.bash
=> fix ncat sctp test and update CI image 

src/commands/teardown.rs, src/dns/aardvark.rs, src/network/bridge.rs
Use the %int suffix for internal network files passed to AV so we can properly trigger DNS handling (or, more accurately, lack of DNS handling) over there. Also, to handle version migrations, if there is a previous file for the network named without the suffix, delete that.
This will unblock [1].
[1] https://github.com/containers/aardvark-dns/pull/447
=> Add suffix to Aardvark internal network filenames

build.rs, src/commands/version.rs, src/firewall/mod.rs
The NETAVARK_DEFAULT_FW environment variable controls the default firewall driver that will be used by the compiled Netavark. Currently supported values are "iptables" (the default, if the environment variable is unset), "nftables", and "none" (we'll add "firewalld" as a supported value once that driver is done).
Unsupported values result in a panic/failure to build.
=> Add conditional compilation of default firewall driver

rpm/netavark.spec
set NETAVARK_DEFAULT_FW to nftables on EL10+.
=> [skip-ci] RPM: switch default firewall to nftables on EL10+

rpm/netavark.spec
On C9S and RHEL9, we've been specifying our own cargo macro which fails to create debuginfo packages with rust 1.77.2. Ref:
https://blog.rust-lang.org/2024/03/21/Rust-1.77.0.html#enable-strip-in-release-profiles-by-default
This can be remedied by simply using the default __cargo macro provided on build environments.
=> [skip-ci] RPM: use default __cargo macro across all envs

.packit.yaml
If the packages key isn't specified, packit will trigger copr jobs for all of `netavark-fedora`, `netavark-centos` and `netavark-rhel`.
=> [skip-ci] Packit: do not create dup jobs on podman-next

Makefile
Although `$(DESTDIR)/$(LIBEXECPODMAN)` will install normally, but the correct path is `$(DESTDIR)$(LIBEXECPODMAN)`.
=> fix: remove extra / in make install and uninstall 

Cargo.lock, Cargo.toml, RELEASE_NOTES.md
* Do not perform namespace detection for aardvark-dns updates as it is not needed
* Fixed condition where ignored errors were being returned as real
* With nftables, only dump netavark table rules
* Fix port forward with strict RPF and multi-networks
=> Release1.11.0

rpm/netavark.spec
The rust-toolset macros in RHEL 10 are now compatible with Fedora's in terms of handling vendoring and automatic generation of license information and bundled provides.
[NO NEW TESTS NEEDED]
=> [CI:BUILD] rpm: Update Rust macro usage

rpm/netavark.spec
The Epoch in spec file needs to be bumped to preserve upgrade path in c10s.
=> Fix Epoch so upgrade path is preserved from Fedora/RHEL.

test/300-macvlan.bats, test/testfiles/metric-macvlan.json
Make sure macvlan supports the metric option, the code did so for a while but there never was a metric test added here and it didn't work in podman[1]. So make sure we test it works and do not regress.
[1] https://github.com/containers/common/issues/2051
=> test: add macvlan metric test

rpm/netavark.spec
This was previously being handled in containers-common but is best handled here.
=> [skip-ci] RPM: handle iptables/nftables dependencies

rpm/netavark.spec
Use nftables as default driver for fedora 41.
https://fedoraproject.org/wiki/Changes/NetavarkNftablesDefault
=> rpm: use nftables as default for f41

src/dns/aardvark.rs
Noticed this while testing my aardvark-dns changes. As we capture the full stderr it includes the final newline from the error text which will then be returned like this to podman. However because all podman always adds a newline to its error output on the cli it resulted in two newlines being printed. Not a bug deal but still unnecessary and confusing.
=> aardvark-dns: trim whitespaces from error text

Cargo.toml
To publish our crate, we must use official categories.  In this case, "virtualization" specifically calls out containers and seems appropriate.
Upstream: https://github.com/rust-lang/crates.io/pull/8930
=> Change nv cargo categories

build.rs, src/dhcp_proxy/cache.rs, src/dhcp_proxy/lib.rs
A new lint check was added[1] that makes sure all cfg values are checked. As such we must tell the compiler which values are valid so it doesn't flag them as unexpected.
[1] https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html#cargorustc-check-cfg-for-buildrsbuild-script
=> silence new rust 1.80 warnings

src/commands/setup.rs, src/commands/teardown.rs, src/dhcp_proxy_client/commands/setup.rs, src/network/validation.rs
Following debug lines don't need any formatters hence removing them.
=> chore: remove superfluous formatters from debug stmt

src/commands/teardown.rs, src/dns/aardvark.rs, test/250-bridge-nftables.bats
If we fail to start make sure to remove the entries again to not leak them in case following starts might work.
=> aardvark: on start failure delete entries again

.packit.yaml
Packit now supports Fedora sidetags to ship multiple package updates in a single bodhi.
Ref: https://packit.dev/docs/fedora-releases-guide/releasing-multiple-packages
The targets for bodhi update should be `fedora-all` and not
fedora-branched as the update is with builds from a sidetag and not the
default tag.
=> [skip-ci] Packit: add sidetag to release with aardvark-dns

src/firewall/nft.rs, test/250-bridge-nftables.bats, test/testfiles/bridge-port-tcp-udp.json
The problem with these match statements to check the rules that they are
hard to keep track of and match 1 to 1 to the rules we generate on
setup. This approach here generates the same rules as setup and uses this
to compare the existing rules against.
Fixes #1068
=> nft: remove port forwarding rules correctly

src/firewall/nft.rs, src/firewall/varktables/types.rs, test/100-bridge-iptables.bats, test/250-bridge-nftables.bats
When a container has port 53 forwarded as well we also add dnst rules
for it. This means depending on the order the container dns traffic
might go to another container not aardvark-dns breaking container name
resolution.
The fix to make sure to insert the rule always first.
Fixes https://github.com/containers/netavark/issues/1079
=> iptables/nftables: add dns dnat rule first

.packit.yaml
This helps to avoid dup downstream jobs. Doesn't affect upstream.
=> [skip-ci] Packit: constrain koji and bodhi to the fedora package

.cirrus.yml, README.md, contrib/container_images/Dockerfile.CentOS9, contrib/container_images/Dockerfile.Fedora, contrib/container_images/Dockerfile.Rust, contrib/container_images/Dockerfile.UbuntuLatest, contrib/container_images/README.md, contrib/container_images/build_and_publish_rust_image.sh
Define 1.76 as our MSRV currently and add a new container image that we use in CI to test that.
=> define MSRV and check for it in CI

src/network/core_utils.rs, src/network/vlan.rs, test-dhcp/001-basic.bats
Stuff needed for CI image update but that seems to have other issues that need to debugged so I just submit the fixes alone https://github.com/containers/netavark/pull/1081
=> rust 1.81 lint fixes and remove NOP dhcp test

.packit.yaml
EPEL targets, which are essentially RHEL + EPEL repos, often contain very old builds of rust, golang and other important tools leading to a lot more failures compared to centos stream.
=> [skip-ci] Packit: Remove epel targets

rpm/netavark.spec
rpmautospec is now present on all active Fedora and CentOS Stream envs so we don't need such changelog manipulation anymore.
=> [skip-ci] RPM: cleanup changelog conditionals

src/network/bridge.rs, test/620-bridge-mode.bats, test/testfiles/bridge-managed.json, test/testfiles/bridge-unmanaged.json
While Linux doesn't support modes on bridges, we use this concept to let the user tell us if they want podman/netavark to own the bridge or not. L3 behaves the same way as before this commit. L2 requires the bridge to exist already, will not setup any sysctls or firewall rules on the host and will not delete the bridge once all containers left.
Fixes #1090
Related: https://github.com/containers/common/pull/2247
=> network: bridge: add support for unmanaged mode

src/firewall/nft.rs, test/250-bridge-nftables.bats, test/testfiles/bridge-port-hostip.json
When we have the same port forwarded with two different host ips there was a rule ambiguity in the NETAVARK-HOSTPORT-DNAT. Each port would have the same jump rule and teardown would have no idea when to remove this rule easily.
To fix this just add the daddr condition to the jump rule as well. That way we know the rule will be unique and there is only one match on teardown.
Fixes #1129
=> nftables: add daddr match to port forward jump rule

src/commands/setup.rs, test/100-bridge-iptables.bats, test/250-bridge-nftables.bats
When aardvark-dns error out at the end we already configured interfaces
+ firewall rules for the driver but because we return a error podman considers this a failure and teardown is never called.
Netavark should always cleanup on its own. So on errors make sure to tear down the drivers again.
Fixes #1121
=> setup: on av errors cleanup again

Cargo.lock, Cargo.toml, contrib/container_images/Dockerfile.Rust
rust 1.83 starts to upgrade the Cargo.lock version field to version 4,
however version 4 support was only added in 1.78 which is newer than our
MSRV 1.76. To ensure cargo respects the MSRV we need to set in the in
Cargo.toml.
And also some dep updates from renovate so I don't have to rebase all the PRs
=> cargo: set rust-version

.gitignore, build.rs, src/dhcp_proxy/lib.rs
We should not create build time generated files under src/, with the latest rust version this seems to cause problems on cargo publish.
Instead just default to the OUT_DIR env that is always set by cargo.
Fixes #1137
=> generate protobuf in OUT_DIR

src/commands/setup.rs, src/commands/teardown.rs, src/dhcp_proxy/dhcp_service.rs, src/dhcp_proxy/types.rs, src/network/driver.rs, src/network/macvlan_dhcp.rs, src/network/types.rs, src/network/vlan.rs, src/proto/proxy.proto, test-dhcp/002-setup.bats, test-dhcp/003-teardown.bats, test-dhcp/005-renew.bats
Currently, since a container's hostname isn't sent to netavark, we can't
include it in DHCP requests when using a macvlan network and DHCP IPAM
driver. Therefore, if DNS records need to be added for a container, it needs
to be done by external scripts.  Another issue is that since every time a
container starts it gets a new random mac address and since, in the absense
of a client id, the mac address is used by DHCP servers to keep track of
leases, it's likely that the container will get a new ip address on restart.
If the container is providing an exposed service, even just ssh, clients may
have the old address cached and may not be able to reach the container.
This commit accepts the container's hostname on incoming JSON setup commands
and adds it to the DHCP client configuration so an …
=> Add container hostname to DHCP requests and use container id as client id

src/network/bridge.rs, src/network/constants.rs, src/network/netlink.rs, test/630-bridge-vlan.bats
Implement a new vlan option that turn the bridge vlan_filtering mode on and then assign the host side veth to the given vlan id.
With that a users should be able to have multiple networks with the same bridge but different vlan ids (we need to change network create logic fo this).
Fixes #1028
=> bridge: add vlan support

src/network/bridge.rs, src/network/core_utils.rs, src/network/dhcp.rs, src/network/mod.rs, src/network/vlan.rs, test/620-bridge-mode.bats, test/testfiles/bridge-managed-dhcp.json
Support DHCP for bridge driver, like macvlan.
Only valid when using the unmanaged bridge mode.
Fixes #868
=> bridge: support DHCP ipam driver

.gitignore, docs/Makefile, docs/netavark-firewalld.7.md, rpm/netavark.spec, src/commands/firewalld_reload.rs, src/firewall/firewalld.rs, src/firewall/fwnone.rs, src/firewall/iptables.rs, src/firewall/mod.rs, src/firewall/nft.rs, src/network/bridge.rs
This mostly amounts to throwing a sensible error in cases where the setting is enabled and the user has requested ports be forwarded.
There are no tests at present because firewalld 2.3.x is currently restricted to Rawhide, and is required for effective testing.
A manpage has also been added with details on how to work with the StrictForwardPorts setting (as well as some other tidbits on firewalld + Podman integration).
=> Add handling for firewalld's StrictForwardPorts setting

docs/netavark-firewalld.7.md, src/firewall/firewalld.rs, test/100-bridge-iptables.bats, test/200-bridge-firewalld.bats, test/250-bridge-nftables.bats
There are two major changes here.
Firstly, this adds proper support for port forwarding from localhost via a new policy accepting traffic from HOST. This is the last bit we were missing from the original port-forwarding implementation.
Secondly, this fixes a bug where we generated incorrect rules when port-forwarding from a single IP. Instead of doing standard port-forwarding rules, those need rich rules. This was reported as #881.
There are also some small code cleanups in how we handle setting up and tearing down port forwarding. It's still rather ugly, but at least a little better than it was before.
Fixes #881
=> Finalize firewalld port forwarding support

.cirrus.yml, test/001-basic.bats
Some distros like openSUSE & Debian don't build netavark from git, so the commit information won't be available.
Make this test conditional when `NETAVARK_UPSTREAM` is set.
=> test/001-basic: Make commit test optional

.cirrus.yml, Cargo.lock, Cargo.toml, Makefile, RELEASE_NOTES.md, contrib/cirrus/runner.sh, docs/Makefile, src/firewall/firewalld.rs, test/001-basic.bats
Release + backports from
https://github.com/containers/netavark/pull/1202
https://github.com/containers/netavark/pull/1191
https://github.com/containers/netavark/pull/1184
=> [v1.14] Release 1.14.1

CONTRIBUTING.md, README.md
This PR adds a link to the c/common contributor's guide. 
Fixes: https://issues.redhat.com/browse/RUN-2321
Note: After the merge https://github.com/containers/common/pull/2386, the contributor's guide will contain sections specific to Golang and Rust.
=> Add link to c/common contributor's guide

src/network/bridge.rs, test/100-bridge-iptables.bats, test/200-bridge-firewalld.bats, test/250-bridge-nftables.bats
Podman will use this as main search domain and ignore everything else then. We don't need to set the search domain at all, aardvark-dns resolves names without it fine.
Fixes: #1133
Fixes: https://issues.redhat.com/browse/RHEL-83787
=> remove search domain from response

Cargo.lock
Somehow renovate created a borken PR by not updating Cargo.lock but it still passed CI. It is not clear what happened but this needs investigation, anyhow for the time being fix the unclean tree by committing the missing Cargo.lock changes.
Fixes: 84ec7510 ("fix(deps): update rust crate netlink-packet-utils to 0.6.0")
=> Cargo.lock: fix desync with Cargo.toml

Cargo.lock, Cargo.toml
So cargo doesn't really care if we list stuff there that we don't use.
Neither serde-value nor netlink-packet-utils were used directly. Also putting the json deps behind a feature makes no sense as we always need that to build and we ar enot a lib. Removing the url feature allos us to drop the url dep as well which we also do not use.
And then while I touch the serde json deps update them to the latest.
=> remove some unused deps

Makefile
Use find to list all source files recursively, the ** doesn't actually seem to work correctly in all cases. It requires the use the the globstar shell option which may or may not be set.
While at it also add Makefile so we rebuild if the Makefile is changed, e.g. when adding new flags to cargo.
Fixes: a08bb557fd ("Makefile: do not rebuild if nothing changed")
=> Makefile: correctly set SOURCES

src/commands/teardown.rs, src/dns/aardvark.rs, src/network/bridge.rs, test/250-bridge-nftables.bats, test/testfiles/dns-invalid-names.json
Since we write space, command and newline separated file these
characters have a special meaning when parsing the file. Any such
character inside the strings can break the parser. We need checks to
disallow these characters.
While it would have been easy to add a check at the time we write the
file there we could not really make a good decision on what to do with
the value. As such I create a newtype which wraps the string but it can
only be constructed via the TryFrom trait. That is enough to gurantee
that any caller must have called the validation code.
Note that we only print a warning and ignore such invalid value, a hard
error might cause compatibility issues as per the issue some automated
tooling generates such names.
Fixes: https://github.com/containers/netavark/issues/1019
Fixes: …
=> aardvark: handle names more safely

Cargo.lock, Cargo.toml, src/firewall/nft.rs
This is a rather large change as it switched to using Cow<> which
requires a fair amount of changes. But in the end it should help to
avoid some copies for at least for the 'static str chain names we have.
=> run cargo update and update nftables to 0.6.2

rpm/netavark.spec
We do support nftables for a while now. Just noticed while checking the fedora builds.
=> rpm: update description

Cargo.lock, Cargo.toml
Contains patch for https://github.com/nispor/mozim/issues/49
Fixes: https://github.com/containers/netavark/issues/811
Closes: RUN-2720
=> cargo: bump `mozim` to `0.2.6`
